<div class="home profile-style promoted-style main sidebar-page-data" data-page-id="<?php echo $wo['PageList']['page_id']?>">
    <div class="card hovercard promoted">
        <div class="cardheader">
            <img src="<?php echo $wo['PageList']['cover']?>" id="cover-image" alt="<?php echo $wo['PageList']['name']?> Cover Image">
        </div>
        <div class="text-shadow"></div>
        <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
            <img id="updateImage-<?php echo $wo['PageList']['page_id']?>" alt="<?php echo $wo['PageList']['name']?> Profile Picture" src="<?php echo $wo['PageList']['avatar']?>">
        </div>
        <div class="info">
            <div class="title">
                <a id="user-full-name" href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username']?>"><?php echo $wo['PageList']['user_name'];?></a>  <?php if ($wo['PageList']['verified'] == 1) { ?> <i class="fa fa-check-circle verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i> <?php } ?>
            </div>
        </div>
    </div>
    <div class="user-like-button sidebar-listed-page-like" data-type="sidebar">
        <?php echo Wo_GetLikeButton($wo['PageList']['page_id']);?>
        <span class="page-likes">
          <?php if (empty($wo['PageList']['view_category'])) { ?>
            <?php echo $wo['PageList']['category'];?>
            <span class="<?php echo Wo_RightToLeft('pull-right');?>">
            <?php echo Wo_CountPageLikes($wo['PageList']['page_id']);?> <i class="fa fa-fw fa-thumbs-up"></i>
            </span>
            <div class="clear"></div>
          <?php } else { ?>
          <br>
          <?php } ?>
        </span>
    </div>
</div>