<?php
if ($wo['page_data']['page_type'] == 0) {
?>
<div class="page-margin">
    <?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
</div>
<?php
} else {
?>
<div class="page-margin">
   <div class="list-group red-list">
      <div class="list-group-item"><?php echo $wo['page_data']['page_title']?></div>
      <div class="setting-well">
        <?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
      </div>
   </div>
</div>
<?php } ?>