<?php
$selected_video_chat_yes = ($wo['config']['video_chat'] == 1) ? ' checked' : '';
$selected_video_chat_no  = ($wo['config']['video_chat'] == 0) ? ' checked' : '';
?>
<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-video-camera"></i> Video chat Setting</div>
   <div class="setting-well page-margin">
      <form action="" method="post" class="admin-site-setting form-horizontal">
        <div class="form-group">
            <label class="col-md-3" for="video_chat">Video chat/calls</label>
            <div class="col-md-5"> 
               <label class="radio-inline" for="video_chat-0">
               <input type="radio" name="video_chat" id="video_chat-0" value="1" <?php echo $selected_video_chat_yes; ?>>
               <?php echo $wo['lang']['enable']; ?>
               </label> 
               <label class="radio-inline" for="video_chat-1">
               <input type="radio" name="video_chat" id="video_chat-1" value="0" <?php echo $selected_video_chat_no; ?>>
               <?php echo $wo['lang']['disable']; ?>
               </label>
            </div>
        </div>

        <hr>
        <div class="form-group">
            <label class="col-md-3" for="smtp_password"></label>  
            <div class="col-md-6">
              <span class="help-block">To start using this feature, you'll need to create an account <a href="http://www.twilio.com" target="_blank">here</a> and buy "Programmable Video" product.</span>
              <?php if (!Wo_isSecure()) { ?>
              <span class="help-block" style="color:red;">Please note that this feature required secured domain and SSL certificate.</span> 
             <?php } ?>
             </div>
         </div>	
         <div class="form-group">
            <label class="col-md-3" for="video_accountSid">Live accountSid</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="video_accountSid" value="<?php echo $wo['config']['video_accountSid'];?>">
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="video_apiKeySid">apiKeySid</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="video_apiKeySid" value="<?php echo $wo['config']['video_apiKeySid'];?>"> 
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="video_apiKeySecret">apiKeySecret</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="video_apiKeySecret" value="<?php echo $wo['config']['video_apiKeySecret'];?>"> 
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="video_configurationProfileSid">ConfigurationProfileSid</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="video_configurationProfileSid" value="<?php echo $wo['config']['video_configurationProfileSid'];?>"> 
            </div>
         </div>
         <hr>
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
         <div class="form-group">
            <label class="col-md-3"></label>  
            <div class="col-md-6">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i>  <?php echo $wo['lang']['save']?>
               </button> 
            </div>
         </div>
      </form>
   </div>
</div>
<script type="text/javascript">
$(function() {
    $('form.admin-site-setting').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_sms_setting',
      beforeSend: function() {
        Wo_progressIconLoader($('form.admin-site-setting').find('button'));
      },
      success: function(data) {
        if (data.status == 200) {
          $('form.admin-site-setting button').html('<i class="fa fa-check"></i> <?php echo $wo["lang"]["saved"];?>');
          setTimeout(function () {
            $('form.admin-site-setting button').html('<i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i>  <?php echo $wo["lang"]["save"]?>');
          }, 2000);
          
          Wo_progressIconLoader($('form.admin-site-setting').find('button'));

        } 
      }
    });
});
</script>