<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-cog"></i><?php echo $wo['lang']['general_setting'];?> <a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['group_name'];?>">(<?php echo $wo['setting']['name'];?>)</a></div>
   <div class="setting-well">
   <form class="setting-general-form form-horizontal" method="post">
      <fieldset>
         <div class="setting-general-alert setting-update-alert"></div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="group_name"><?php echo $wo['lang']['group_name'];?></label>  
            <div class="col-md-6">
               <input id="group_name" name="group_name" type="text" class="form-control input-md" value="<?php echo $wo['setting']['group_name']?>" onkeyup="Wo_CheckGroupname(this.value, <?php echo $wo['setting']['id'];?>);" autocomplete="off">
               <span class="help-block checking"></span>  
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-2" for="group_title"><?php echo $wo['lang']['group_title'];?></label>  
            <div class="col-md-6">
               <input name="group_title" id="group_title" type="text" class="form-control input-md" value="<?php echo $wo['setting']['group_title']?>" autocomplete="off">
            </div>
         </div>
         <!-- Select Basic -->
         <div class="form-group">
            <label class="col-md-2" for="group_category"><?php echo $wo['lang']['category'];?></label>
            <div class="col-md-6">
               <select id="group_category" name="group_category" class="form-control">
                  <?php 
                  foreach ($wo['page_categories'] as $categorie_id => $category) {
                    $selected_contry = ($categorie_id == $wo['setting']['category_id']) ? ' selected' : '' ;
                  ?>
                  <option value="<?php echo $categorie_id;?>" <?php echo $selected_contry;?> ><?php echo $category;?></option>
                  <?php } ?>
               </select>
            </div>
         </div>
         <!-- Textarea -->
         <div class="form-group">
            <label class="col-md-2" for="about"><?php echo $wo['lang']['about'];?></label>
            <div class="col-md-6">             
               <?php 
               $text = br2nl($wo['setting']['about']);
               ?>  
               <textarea class="form-control" id="about" name="about" cols="20" rows="3"><?php echo $text;?></textarea>
            </div>
         </div>
         <div class="form-group last-btn">
            <label class="col-md-2"></label>
            <div class="col-sm-3">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i> <?php echo $wo['lang']['save']; ?>
               </button>
            </div>
         </div>
         <input type="hidden" name="group_id" value="<?php echo $wo['setting']['id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
      </fieldset>
   </form>
</div>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-general-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=groups&s=update_general_settings',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-general-form').find('button'));
    },
    success: function(data) {
      scrollToTop();
      if (data.status == 200) {
        $('.setting-general-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
           $(this).delay(2500).slideUp(500, function() {
              $(this).remove();
            });
        });
      } else {
          var errors = data.errors.join("<br>");
          $('.setting-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
          $('.alert-danger').fadeIn(300);
      }
      Wo_progressIconLoader($('form.setting-general-form').find('button'));
    }
  });
});
</script>