<div class="page-margin">
   <div class="row">
      <div class="col-md-2"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
      <div class="col-md-7">
        <div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-shopping-cart"></i> <?php echo $wo['lang']['my_products'] ?><span class="<?php echo Wo_RightToLeft('pull-right'); ?>" ><a data-ajax="?link1=new-product" href="<?php echo Wo_SeoLink('index.php?link1=new-product');?>"><?php echo $wo['lang']['new'] ?></a></span></div>
            <?php
               $products = Wo_GetProducts(array('user_id' => $wo['user']['user_id']));
               if (count($products) > 0) {
                  foreach ($products as $wo['product']) {
                      echo Wo_LoadPage('products/product-style');
                  }
               } else {
                  echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_available_products'] . '</h5>';
               }
               
               ?>
            <div class="clear"></div>
      </div>
      </div>
      <!-- .col-md-8 -->
      <?php echo Wo_LoadPage('sidebar/content');?>
   </div>
   <!-- .row -->
</div>
<script>
$(function () {
	$('.products-hover').hover(function () {
      var $this = $(this);
      $this.find('#overlay-black').addClass('overlay-black').fadeIn(200);
      $this.find('.game-name').fadeIn(200);
    }, function () {
      var $this = $(this);
      $this.find('#overlay-black').removeClass('overlay-black').fadeOut(400);
      $this.find('.game-name').fadeOut(200);
    });
});
</script>