<div class="profile-style" id="member-<?php echo $wo['member']['user_id'] ?>">
   <a href="<?php echo $wo['member']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['member']['username']?>">
      <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
         <img src="<?php echo $wo['member']['avatar'];?>" alt="<?php echo $wo['member']['name']; ?> Profile Picture" />
      </div>
      <?php echo $wo['member']['name']; ?>
   </a>
   <div class="page-website">
      <?php echo Wo_UserStatus($wo['member']['user_id'],$wo['member']['lastseen']); ?>
   </div>
   <div>
   <span onclick="Wo_DeleteJoinedUser(<?php echo $wo['member']['user_id']?>, <?php echo $wo['setting']['id']?>);" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> <?php echo $wo['lang']['remove']; ?></span>
   </div>
</div>