<?php 
$pages = Wo_GetCustomPages();
?>
<div class="page-margin">
   <div class="footer-wrapper">
      <hr>
      <ul class="list-inline <?php echo Wo_RightToLeft('pull-left');?>">
         <li><a data-ajax="?link1=home" href="<?php echo $wo['config']['site_url'];?>"><?php echo $wo['lang']['home'];?></a></li><li> - </li>
         <li><a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a></li><li> - </li>
         <li><a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a></li><li> - </li>
         <li><a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a></li><li> - </li>
         <li><a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a></li><li><?php if ($wo['config']['developers_page'] == 1)  { ?> - </li>
         <li><a data-ajax="?link1=terms&type=developers" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=developers');?>"><?php echo $wo['lang']['developers'];?></a></li><?php } ?>
         <?php
         if (count($pages) > 0) {
               ?>
                  <li>-</li>
                  <?php
               }
          ?>
          <li>
         <div class="dropdown dropup">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
             <?php echo $wo['lang']['more'];?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" style="width: auto; min-width: 100px; font-size: 11px;">
               <?php
               if (count($pages) > 0) {
                  foreach ($pages as $key => $page) {
                  ?>
                  <li><a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a></li>
                  <?php
                 }
               }
               ?>
            </ul>
         </div>
         </li> 
      </ul>
      <div class="<?php echo Wo_RightToLeft('pull-right');?>">
         <div class="dropdown dropup">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
               <?php
               $langs = Wo_LangsNamesFromDB();
               if (count($langs) > 0) {
                   foreach ($langs as $key => $wo['langs']) {
                     $language = $wo['langs'];
                     $languages_name = ucfirst($wo['langs']);
                     $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
                ?>
               <li><a href="<?php echo $link;?>"><?php echo $languages_name;?></a></li>
               <?php } } ?>
            </ul>
         </div>
      </div>
      <div class="clear"></div>
      <div class="footer-powered">
      </div>
   </div>
</div>

<div class="rights" style="padding-top: 20px;
    height: 60px;
    font-family: 'Lato', sans-serif;
    background: #1b1b1b;">
    <div class="container">
      <div class="<?php echo Wo_RightToLeft('pull-left'); ?>">
         <p style="color: #999999; font-size: 12px; display: inline-block;"><?php         $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
        echo $copy = str_replace('{date}', date('Y'), $copy);?></p>
      </div>
      <div class="<?php echo Wo_RightToLeft('pull-right');?>">
      <ul class="list-inline <?php //echo Wo_RightToLeft('pull-left');?>">
            <li><a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a></li>
            <li><a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a></li>
            <li><a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a></li>
            <li><a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a></li>
            <li>         <div class="dropdown dropup">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
               <?php
               $langs = Wo_LangsNamesFromDB();
               if (count($langs) > 0) {
                   foreach ($langs as $key => $wo['langs']) {
                     $language = $wo['langs'];
                     $languages_name = ucfirst($wo['langs']);
                     $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
                ?>
               <li><a href="<?php echo $link;?>"><?php echo $languages_name;?></a></li>
               <?php } } ?>
            </ul>
         </div>
</li>
         </ul>
         

      </div>
   </div>
</div>