<div class="rights">
   <div class="container">
      <div class="page-margin">
         <div class="footer-wrapper sidebar">
             <hr>
                  <a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a>
                  <a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a>
                  <a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a>
                  <a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a>
                  <?php
                              $pages = Wo_GetCustomPages();
                              if (count($pages) > 0) {
                                 foreach ($pages as $key => $page) {
                                 ?>
                                 <a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a>
                                 <?php
                                }
                              }
                              ?>

            <div class="pull-right">
               <span class="dropdown dropup">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
                             <?php
                             foreach (Wo_GetLanguages() as $lang) {
                                $language = str_replace(".php", "" ,$lang);
                                $languages_name = ucfirst(strtolower($language));
                                $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
                              ?>
                             <li><a class="lang" href="<?php echo $link;?>"><?php echo $languages_name;?></a></li>
                             <?php } ?>
                          </ul>
                       </span>

            </div>
     
            <div class="clear"></div>
            <div class="footer-powered">
            <?php $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
         echo $copy = str_replace('{date}', date('Y'), $copy); ?>
               <?php //echo $wo['lang']['copyrights'];?>
            </div>
         </div>
      </div>  
   </div>
</div>
<!-- <div class="welcome-footer">
	
	
</div>
<div class="welcome-footer-right">
	
</div> -->