<div id="newsection-alert"></div>
<div class="setting-well page-margin">
	<form class="form" id="newsection">
		<div class="form-group">
			<div class="col-md-1"></div>
			<label for="name" class="col-md-2">
				Name
			</label>
			<div class="col-md-9">
				<input type="text" name="name" class="form-control">
			</div>
			<div class="clear"></div>
		</div>	
		<div class="form-group">
			<div class="col-md-1"></div>
			<label for="description" class="col-md-2">
				Description
			</label>
			<div class="col-md-9">
				<textarea name="description" id="description" class="form-control"></textarea>
			</div>
			<div class="clear"></div>
		</div>
		<div class="form-group">
			<div class="col-md-1"></div>
			<label for="name" class="col-md-2">
				
			</label>
			<div class="col-md-9">
				<button type="submit" class="btn btn-main">
               		<i class="fa progress-icon fa-plus" data-icon="plus"></i> Add
               </button>
			</div>
			<div class="clear"></div>
		</div>
		<input type="reset" class="hidden">
	</form>	
</div>

<script>
	jQuery(document).ready(function($) {
		
        $('#newsection').ajaxForm({

          url: Wo_Ajax_Requests_File()  +  '?f=new-forum-section&hash=' + $('.main_session').val(),
          beforeSend: function() {
            Wo_progressIconLoader($('#newsection').find('button'));
          },
          type:'POST',
          dataType: 'json',
          success: function(data) {
            scrollToTop();
            if (data['status'] == 200) {
                
                $("#newsection-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                $("#newsection input[type=reset]").click();
                window.location.reload();
            }else{
                
                $("#newsection-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
            } 
            Wo_progressIconLoader($('#newsection').find('button'));
            
          }
        });

	});
</script>