<?php $sections = Wo_GetForumSec(array('forums'=>false,'limit'=>500000, 'order_by' => 'DESC')) ?>
<?php if (count($sections)): ?>

<table class="table table-striped custab">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <?php foreach ($sections as $section): ?>
        <tr data-rmd-section-ident="<?php echo $section['id']; ?>">
            <td><?php echo $section['id']; ?></td>
            <td class="small"><?php echo $section['section_name']; ?></td>
            <td class="small"><?php echo $section['description']; ?></td>
            <td class="text-center">
            <div class="btn-group">
                <button class="btn main btn-default delete-section" id="<?php echo $section['id'];?>">
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                </button>
            </div>
        </td>
    </tr>
    <?php endforeach;?>

</table>
<?php echo Wo_loadPage('admin/forum/includes/delete-section'); ?>


<?php else: ?>
   <?php echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_sections_found'] .  '</h5>'; ?>
<?php endif; ?>