<?php 
/* update views */
Ads::updateAd($ad); 
if($ad['type'] == 'website'){ ?>
<ul class="list-group"><li class="panel-widget ads-side">
<div class="head">

<?php include "ads_random_btn.phtml"; ?>

<span><img class="fa fa-fw mr5" src="<?php echo $wo['config']['theme_url'];?>/img/promote.png" alt="ads" title="ads"><?php echo $wo['lang']['plugin_ads_sponsored']; ?></span></div>
    <div class="ad-image">
        <a class="ads-click-link" data-id="<?php echo $ad['id']; ?>" onclick="return window.open('<?php echo $ad['link']; ?>')" href="javascript:void(0)" data-ajaxify="true"><img src="<?php echo $ad['images']; ?>"></a>
    </div>
<h5 class="ad-title"><a class="ads-click-link" data-id="<?php echo $ad['id']; ?>" onclick="return window.open('<?php echo $ad['link']; ?>')" href="javascript:void(0)"><?php echo $ad['title']; ?></a> </h5>
<a class="ads-click-link" data-id="<?php echo $ad['id']; ?>" onclick="return window.open('<?php echo $ad['link']; ?>')" href="javascript:void(0)"><?php echo $ad['display_link']; ?></a>
<p class="ad-description"><?php echo $ad['description']; ?></p>
</li> 
</ul>
<?php } else if($ad['type'] == 'page'){ ?>

<?php $info_ads_page = Ads::get_page($ad['page_id']); //echo json_encode($info_ads_page); ?>
<ul class="list-group"><li class="panel-widget ads-side post-media">
    <div class="head">

<?php include "ads_random_btn.phtml"; ?>

	<span><img class="fa fa-fw mr5" src="<?php echo $wo['config']['theme_url'];?>/img/promote.png" alt="ads" title="ads"><?php echo $wo['lang']['plugin_ads_suggested-page']; ?></span></div>
    <div class="second-head">
        <div class="media">
            <div class="media-object pull-left">
                <a class="ads-click-link" data-id="<?php echo $ad['id']; ?>" href="<?php echo $wo['config']['site_url'].'/'.$info_ads_page['page_name']; ?>" data-ajaxify="true"><img width="40" height="40" src="<?php echo $info_ads_page['photo']; ?>"></a>
            </div>
            <div class="media-body">
                <h5 class="media-heading"><a class="ads-click-link" href="<?php echo $wo['config']['site_url'].'/'.$info_ads_page['page_name']; ?>" data-ajaxify="true"><?php echo $info_ads_page['page_title']; ?></a></h5>
                <?php echo Wo_GetLikeButton($info_ads_page['page_id']); ?></span>
				<span class="<?php echo Wo_RightToLeft('pull-right');?>">
   			      <?php echo Wo_CountPageLikes($info_ads_page['page_id']); ?><i class="fa fa-fw fa-thumbs-up"></i>
   			    </span> 
				</div>
        </div>
    </div>
    <p class="ad-description"><?php echo $ad['description']; ?></p>
    <div class="ad-image"><a class="ads-click-link" data-id="<?php echo $ad['id']; ?>" href="<?php echo $wo['config']['site_url'].'/'.$info_ads_page['page_name']; ?>" data-ajaxify="true"><img src="<?php echo $ad['images']; ?>"></a></div>
</li></ul>
<?php } ?>