<?php /* page content */ 
	//get ads lists
	$payments = Ads::get_payment_lists("", FALSE, FALSE, " id DESC ", " user_id='{$wo['user']['user_id']}' ");
?>
<div class="container mt20">
		<div class="col-md-11">
			<?php /* left panel */ ?>
			<div class="col-sm-12" style="padding:0px;"><?php include "ads_header.phtml"; ?></div>
			<?php /* left panel */ ?>
				
		<?php /* content */?>
		<div class="col-md-12 panel panel-default">

        <div class="panel-body with-table">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover js_dataTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
							<th>Cost</th>
                            <th>Quantity</th>
							<th>Txn</th>
							<th>Payment</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($payments as $row){ ?>
                        <tr>
                            <td><a target="_blank" href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=ads-edit&ad_id=1"><?php echo $row['id']; ?></a></td>
                            <td><?php echo $row['payment_type']; ?></td>
							<td><?php echo $row['payment_amount']; ?> <?php echo $row['payment_currency']; ?></td>
                            <td><?php echo $row['quantity']; ?></td>
							<td><?php echo $row['txn_id']; ?></td>
							<td><?php echo date('Y-m-d H:i:s', $row['created']); ?></td>
                            <td>
                          <button class="btn btn-xs btn-danger js_admin-deleter" data-handle="payment" data-id="<?php echo $row['id']; ?>"><i class="fa fa-trash-o"></i></button>                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
				
</div>
		<?php /* content */ ?>		
		</div>
		<?php /* left panel */ ?>
</div>
<?php /* page content */ ?>