<?php /* Ads */ ?>
<script>
	function load_ads_post(id){ 
		if($('.posts_load .post').length == 0){ setTimeout('load_ads_post(0)', 10000); return false; }
		$.ajax({type: 'post', url: site_ajax+ "?f=ads_post", cache : false, 
            success : function(result) { 
				if(result){
					if(id == 0){ 
						$('.posts_load .post:eq(1)').closest('.post-container').before(result.data);
					} else { 
						$('#post-'+id).closest('.post-container').before(result.data);
					}
				}
			}
        });
    }
	
__['There is no more data to show']	= '<?php echo $wo['lang']['plugin_no_more_data']; ?>';		
<?php /*
__['Active'] = '<?php echo $wo['lang']['plugin_ads_active']; ?>';
__['Ads Actived'] = '<?php echo $wo['lang']['plugin_ads_ads_actived']; ?>';
__['This ads is actived!'] = '<?php echo $wo['lang']['plugin_ads_this_ads_is_actived']; ?>';
__['Delete Ads'] = '<?php echo $wo['lang']['plugin_ads_delete_ads']; ?>';
__['Are you sure you want to delete this ads?'] = '<?php echo $wo['lang']['plugin_ads_delete_this_ads']; ?>';
__['Delete Plan'] = '<?php echo $wo['lang']['plugin_ads_delete_plan']; ?>';
__['Are you sure you want to delete this plan?'] = '<?php echo $wo['lang']['plugin_ads_delete_this_plan']; ?>';
*/ ?>
</script>