<?php /* pokes */
  //get pokes
     $pokes = Poke::get_pokes($wo['user']['user_id']);
  
  // get profile friends
     $friends_count = count(Wo_GetFollowing($wo['user']['user_id'],'sidebar',10));
   
  // get profile friends_suggest
    $friends = array();
	if($friends_count > 0) { $friends = Poke::get_friends($wo['user']['user_id']); }
	
 ?>
<div class="content_pokes">       
        <?php /* center panel 1 */ ?>
                <div class="panel panel-default">
                    <div class="panel-heading light clearfix mt5">
                        <div class="col-sm-6">
                            <strong><?php echo $wo['lang']['plugin_poke_pokes']; ?></strong>
						</div>	
						<div class="col-sm-6">
<input type="text" name="toque" class="text_search_toque" placeholder="<?php echo $wo['lang']['plugin_poke_poke_search_friend']; ?>"/>
	<div class="dropdown-menu_page page_auto-complete" id="list_f_pokes"><ul id="typeahead_list_f_poke"></ul></div>
	                     </div>
                        
                    </div>
                    <div class="panel-body row">
                        <?php if(count($pokes) > 0){ ?>
                            <ul>
                                <?php foreach($pokes as $poke){ ?>
                                <?php include "ajax.poke.phtml"; ?>
                                <?php } //F ?>
                            </ul>
                        <?php } else { ?>
                            <p class="text-center text-muted">
                                <?php echo $wo['lang']['plugin_poke_poke_no_available']; ?>
                            </p>
                        <?php } ?>

                    </div>
                </div>
        <?php /* center panel 1 */ ?>
		
		<?php /* center panel 2 */ ?>
                <div class="panel panel-default">
                    <div class="panel-heading light clearfix">
                        <div class="mt5">
                            <strong><?php echo $wo['lang']['plugin_poke_poke_suggest']; ?></strong>
                        </div>
                    </div>
                    <div class="panel-body row">
                        <?php if(count($friends) > 0){ ?>
                            <ul>
                                <?php foreach($friends as $friend){ ?>
                                <?php include "ajax.poke_suggest.phtml"; ?>
                                <?php } //F ?>
                            </ul>
                        <?php } else { ?>
                            <p class="text-center text-muted">
                                <?php echo $wo['lang']['plugin_poke_poke_suggest_no_available']; ?>
                            </p>
                        <?php } ?>

                    </div>
                </div>
            
        <?php /* center panel 2 */ ?>
</div>