<div class="filter-margin">
   <div class="btn-group filter-container">
      <button type="button" onclick="Wo_FilterPostBy('all');" class="btn filter btn-main type-all">
      <i class="fa fa-bars progress-icon" data-icon="bars"></i>
      <span class="filter-text"> <?php echo $wo['lang']['all']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('text');" class="btn filter btn-main type-text">
      <i class="fa fa-pencil progress-icon" data-icon="pencil"></i>
      <span class="filter-text"> <?php echo $wo['lang']['text']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('photos');" class="btn filter btn-main type-photos">
      <i class="fa fa-file-image-o progress-icon" data-icon="file-image-o"></i>
      <span class="filter-text"> <?php echo $wo['lang']['photos']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('video');" class="btn filter btn-main type-video">
      <i class="fa fa-film progress-icon" data-icon="film"></i>
      <span class="filter-text"> <?php echo $wo['lang']['videos']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('music');" class="btn filter btn-main type-music">
      <i class="fa fa-music progress-icon" data-icon="music"></i>
      <span class="filter-text"> <?php echo $wo['lang']['sounds']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('files');" class="btn filter btn-main type-files">
      <i class="fa fa-file-text-o progress-icon" data-icon="file-text-o"></i>
      <span class="filter-text"> <?php echo $wo['lang']['files']; ?><span>
      </button>
      <button type="button" onclick="Wo_FilterPostBy('maps');" class="btn filter btn-main type-maps">
      <i class="fa fa-map-marker progress-icon" data-icon="map-marker"></i>
      <span class="filter-text"> <?php echo $wo['lang']['maps']; ?><span>
      </button>
   </div>
</div>