<div class="profile-style">
   <a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
      <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
         <img src="<?php echo $wo['page']['avatar'];?>" alt="<?php echo $wo['page']['page_name']; ?> Profile Picture" />
      </div>
      <?php echo $wo['page']['page_title']; ?>
   </a>
   <div class="page-website">
      <?php echo $wo['lang']['category'];?>: <?php echo $wo['page']['category']; ?>
   </div>
   <a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' .  $wo['page']['page_name']); ?>" data-ajax="?link1=page-setting&page=<?php echo $wo['page']['page_name'];?>" class="btn btn-default btn-sm"><i class="fa fa-pencil-square-o"></i> <?php echo $wo['lang']['edit']; ?></a>
</div>