<div class="col-md-12 events-list-wrapper" data-event="<?php echo($wo['event']['id']);?>">
	<div class="row">
			<div class="events-list-cover">
			    <a href="<?php echo $wo['event']['url']; ?>">
			    <img src="<?php echo $wo['event']['cover']; ?>" class="events-list-cover-img">
				<p class="events-list-name">
					<?php echo $wo['event']['name']; ?>
				</p>
                </a>
			</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
