<?php
$page_name = '';
$page_icon = '';
switch ($wo['active']) {
		case 1:
			$page_name = $wo['lang']['events'];
			break;
		case 2:
			$page_name = $wo['lang']['going'];
			break;
		case 3:
			$page_name = $wo['lang']['invited'];
			break;
		case 4:
			$page_name = $wo['lang']['interested'];
			break;
		case 5:
			$page_name = $wo['lang']['past'];
			break;
		case 6:
			$page_name = $wo['lang']['create'];
			break;
		case 7:
			$page_name = $wo['lang']['my_events'];
			break;
		default:
	}	
?>
<div class="page-margin">
   <div class="row">
      <div class="col-md-2"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
      <div class="col-md-7 profile-lists">
        <div class="list-group events-content-wrapper">
        <div class="list-group-item">
               <i class="fa fa-calendar-o fa-fw"></i> <?php echo $page_name;?>
               <span class="<?php echo Wo_RightToLeft('pull-right');?>">
			   <a href="<?php echo Wo_SeoLink('index.php?link1=create-event'); ?>" style="float: left;margin-right: 7px;"><?php echo $wo['lang']['create']; ?></a>
                  <div class="dropdown" style="float: right;">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">
					    <span class="caret"></span></a>
					    <ul class="dropdown-menu post-options">
					      <li><a href="<?php echo Wo_SeoLink('index.php?link1=events-going'); ?>"><?php echo $wo['lang']['going']; ?>	</a></li>
					      <li><a href="<?php echo Wo_SeoLink('index.php?link1=events-invited'); ?>"><?php echo $wo['lang']['invited']; ?></a></li>
					      <li><a href="<?php echo Wo_SeoLink('index.php?link1=events-interested'); ?>"><?php echo $wo['lang']['interested']; ?></a></li>
					      <li><a href="<?php echo Wo_SeoLink('index.php?link1=events-past'); ?>"><?php echo $wo['lang']['past']; ?></a></li>
					      <li><hr></li>
					      <li><a href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>"><?php echo $wo['lang']['my_events']; ?></a></li>					      
					    </ul>
				  </div>
               </span>
               <div class="clear"></div>
            </div>
		    <div  class="tab-content list-group" style="box-shadow: none;">