<div class="home-sidebar profile-style invitation-users-cont" data-hide-invited-user="<?php echo $wo['user']['id']; ?>">
    <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
            <img src="<?php echo $wo['user']['avatar'];?>" alt="<?php echo $wo['user']['name']; ?> Profile Picture" />
     </div>
     <span class="user-popover" data-id="<?php echo $wo['user']['id'];?>" data-type="<?php echo $wo['user']['type'];?>">
    <a href="<?php echo $wo['user']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username']?>">
        <span class="user-name">
            <?php echo $wo['user']['name']; ?>
            <?php  if($wo['user']['verified'] == 1) {   ?>
            <span class="verified-color">
            <i class="fa fa-check-circle" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
            </span>
            <?php  } ?>
        </span>
    </a>
    </span>
    <div class="<?php echo Wo_RightToLeft('pull-right');?> user-follow-btn">
        <div class="user-follow-button">
            <button class="btn btn-default <?php echo Wo_RightToLeft('pull-right') ?>" onclick="Wo_SendEventInvation($(this).attr('data-invited-user'))" data-invited-user="<?php echo $wo['user']['id']; ?>">
			<?php echo $wo['lang']['invite']; ?>
		</button>
        </div>
    </div>
</div>