<?php
$signup_invite = ( isset($_POST['signup_invite']) ? $_POST['signup_invite'] : ( isset($_GET['signup_invite']) ? $_GET['signup_invite'] : '' ) );
$signup_referer = ( isset($_POST['signup_referer']) ? $_POST['signup_referer'] : ( isset($_GET['signup_referer']) ? $_GET['signup_referer'] : '' ) );

echo Wo_LoadPage('welcome/welcome-header');
$fields = Wo_GetWelcomeFileds();
?>
<div class="wrapper">
 <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  <form class="login" id="register" method="post">
    <p class="title"><?php echo $wo['lang']['sign_up']?></p>
    <input name="username" type="text" placeholder="<?php echo $wo['lang']['username'];?>" autofocus/>
    <i class="fa fa-user"></i>
    <input name="email" type="text" placeholder="<?php echo $wo['lang']['email_address'];?>" />
    <i class="fa fa-envelope-o"></i>
    <?php if($wo['config']['sms_or_email'] == 'sms') {?>
    <input name="phone_num" type="text" placeholder="<?php echo $wo['lang']['phone_num_ex'];?>" />
    <i class="fa fa-phone"></i>
    <?php } ?>
    <input name="password" type="password" placeholder="<?php echo $wo['lang']['password'];?>" />
    <i class="fa fa-key"></i>
    <input name="confirm_password" type="password" placeholder="<?php echo $wo['lang']['confirm_password'];?>" />
    <i class="fa fa-key"></i>
    <?php 
    if (!empty($fields) && count($fields) > 0) {
      foreach ($fields as $key => $wo['field']) {
        echo Wo_LoadPage('welcome/fields');
      }
    }
    ?>
    <select name="gender" id="gender" class="form-control">
      <option value="male"><?php echo $wo['lang']['male'];?></option>
      <option value="female"><?php echo $wo['lang']['female'];?></option>
    </select>

	<?php /*plugin invite and refer*/ 
	/* plugin points */
			if(!empty($wo['plugin_list']['plugin_actived']) && in_array('Points', $wo['plugin_list']['plugin_actived']) && !empty($wo['system']['userpoints_enable']) && $wo['system']['userpoints_enable']){
	?>
	<div class="form-group">
		<a onclick="$(this).parent().find('.input_invite').toggleClass('x-hidden');"><small><?php echo $wo['lang']['plugin_point_i_have_invitation'];?></small><a>
		<div class="input_invite<?php if(empty($signup_referer)){ echo ' x-hidden'; } ?>">
			<input type="text" name="signup_invite" value="<?php echo $signup_invite; ?>" placeholder="<?php echo $wo['lang']['plugin_point_invitation_code'];?>">
		</div>	
	</div>
	<input type="hidden" name="signup_referer" value="<?php echo $signup_referer; ?>">	
    <?php } /* plugin points */ ?>
	
    <?php if($wo['config']['reCaptcha'] == 1) {?>
    <div class="form-group" style="margin-top:10px;">
      <div class="g-recaptcha" data-sitekey="<?php echo $wo['config']['reCaptchaKey']?>"></div>
    </div>
    <?php } ?>
    <?php if(!empty( $_GET['last_url'])){?>
    <div class="form-group">
      <input type="hidden" name="last_url" value="<?php echo urldecode($_GET['last_url']);?>">
    </div>
    <?php } ?>
    <p class="terms"><?php echo $wo['lang']['terms_agreement'] ?> <Br><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'] ?></a></p>
    <button>
    <i class="spinner"></i>
    <span class="state"><i class="fa fa-sign-in"></i> <?php echo $wo['lang']['lets_go'];?></span>
    </button>
  </form>
  <?php echo Wo_LoadPage('footer/welcome');?>
</div>
<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
<script>
var working = false;
var $this = $('#register');
var $state = $this.find('button > .state');
var register_button_text = "<i class='fa fa-sign-in'></i> <?php echo $wo['lang']['lets_go']?>";
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=register',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state.html('<?php echo $wo['lang']['please_wait'] ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $this.addClass('ok');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else if (data.status == 300) {
        window.location.href = data.location;
      } else {
        $state.html(register_button_text);
        $this.removeClass('ok loading', function () {
         $state.html(data.errors);
        });
      } 
      working = false;
    }
  });
  $('#register input').on('click', function(e) {
   $state.html(register_button_text);
  });
});
</script>