  <div class="top-welcome">
  <div class="container">
    <div class="dropdown lang">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
         <?php
         $langs = Wo_LangsNamesFromDB();
         if (count($langs) > 0) {
             foreach ($langs as $key => $wo['langs']) {
               $language = $wo['langs'];
               $languages_name = ucfirst($wo['langs']);
               $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
          ?>
         <li><a href="<?php echo $link;?>"><?php echo $languages_name;?></a></li>
         <?php } } ?>
      </ul>
    </div>

    <div class="logo"><?php echo Wo_LoadPage('welcome/welcome-header-logo');?> </div>
    <?php echo Wo_LoadPage('welcome/welcome-header-register');?>
  </div>
</div>
<?php //echo Wo_LoadPage('welcome/welcome-header-register');?>
<div class="wrapper">
  <div class="typing-element"></div>
  <form class="login" id="login" method="post">
    <p class="title"><?php echo $wo['lang']['login']?></p>
    <input name="username" type="text" placeholder="<?php echo $wo['lang']['username']?>" autofocus/>
    <i class="fa fa-user"></i>
    <input name="password" type="password" placeholder="<?php echo $wo['lang']['password']?>" />
    <i class="fa fa-key"></i>
    <a href="<?php echo Wo_SeoLink('index.php?link1=forgot-password');?>"><?php echo $wo['lang']['forget_password']?></a>
    <div class="text-center">
      <hr>
      <?php if($wo['config']['facebookLogin'] != 0): ?>
      <a href="<?php echo $wo['facebookLoginUrl']?>" class="btn btn-social-icon btn-facebook">
      <i class="fa fa-facebook"></i>
      </a>
      <?php endif; ?>
      <?php if($wo['config']['googleLogin'] != 0): ?>
      <a href="<?php echo $wo['googleLoginUrl']?>" class="btn btn-social-icon btn-google">
      <i class="fa fa-google"></i>
      </a>
      <?php endif; ?>
      <?php if($wo['config']['twitterLogin'] != 0): ?>
      <a href="<?php echo $wo['twitterLoginUrl']?>" class="btn btn-social-icon btn-twitter">
      <i class="fa fa-twitter"></i>
      </a>
      <?php endif; ?>
      <?php if($wo['config']['linkedinLogin'] != 0): ?>
      <a href="<?php echo $wo['linkedInLoginUrl']?>" class="btn btn-social-icon btn-linkedin">
      <i class="fa fa-linkedin"></i>
      </a>
      <?php endif; ?>
      <?php if($wo['config']['VkontakteLogin'] != 0): ?>
      <a href="<?php echo $wo['VkontakteLoginUrl']?>" class="btn btn-social-icon btn-vk">
      <i class="fa fa-vk"></i>
      </a>
      <?php endif; ?>
      <?php if($wo['config']['instagramLogin'] != 0): ?>
      <a href="<?php echo $wo['instagramLoginUrl']?>" class="btn btn-social-icon btn-instagram">
      <i class="fa fa-instagram"></i>
      </a>
      <?php endif; ?>
    </div>
    <button type="submit">
    <i class="spinner"></i>
    <span class="state"><i class="fa fa-sign-in"></i> <?php echo $wo['lang']['login']?></span>
    </button>
  </form>
  

  <?php echo Wo_LoadPage('footer/welcome');?>
</div>
<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
<script>
var working = false;
var $this = $('#login');
var $state = $this.find('button > .state');
var login_button_text = '<i class="fa fa-sign-in"></i> <?php echo $wo['lang']['login']?>';
$(function() {
  $('#login').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=login',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state.html('<?php echo $wo['lang']['authenticating'] ?>');
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
      	$this.addClass('ok');
        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
        setTimeout(function () {
        	window.location.href = data.location;
        }, 1000);
      } else {
        var errors = data.errors.join("<br>");
        $state.html(login_button_text);
        $this.removeClass('ok loading', function () {
        	$state.html(errors);
        });
      } 
      working = false;
    }
  });
  $('#login input').on('click', function(e) {
  	$state.html(login_button_text);
  });
});
</script>
<script>
  $(function(){
      $(".typing-element").typed({
        strings: ["<?php echo 'Social Network. Meet people from all over the world.' ?> <span class='typed-cursor'>|</span>", "<?php echo $wo['lang']['share_your_memories'] ?> <span class='typed-cursor'>|</span>", "<?php echo $wo['lang']['create_new_relationships'] ?> <span class='typed-cursor'>|</span>", "<?php echo 'Social Network. Meet people from all over the world.' ?> <span class='typed-cursor'>|</span>"],
        typeSpeed: 0,
        startDelay: 1000,
        backDelay: 2500,
        shuffle: false,
        cursorChar: "",
      });
  });
</script>
