<span id="Follow-<?php echo $wo['follow']['user_id']?>">
    <button type="button" onclick="Wo_RegisterFollow(<?php echo $wo['follow']['user_id'];?>, <?php echo ($wo['follow']['confirm_followers'] == 1) ? 1 : 0;?>)" class="btn btn-default btn-sm">
       <i class="fa fa-plus-square progress-icon" data-icon="plus-square"></i>
       <span class="button-text"> <?php echo $wo['lang']['follow'];?></span>
    </button>
</span>