<span id="join-<?php echo $wo['join']['id']?>">
    <button type="button" onclick="Wo_RegisterGroupJoin(<?php echo $wo['join']['id'];?>, <?php echo ($wo['join']['join_privacy'] == 2) ? 1 : 0;?>)" class="btn btn-default btn-sm">
       <i class="fa fa-plus-circle progress-icon" data-icon="plus-circle"></i>
       <span class="button-text"> <?php echo $wo['lang']['join'];?></span>
    </button>
</span>