<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-share"></i> <?php echo $wo['lang']['social_links'];?> <?php if(Wo_IsAdmin() === true) { ?><a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['page_name'];?>">(<?php echo $wo['setting']['name'];?>)</a><?php } ?></div>
   <div class="setting-well">
   <form  method="post" class="form-horizontal setting-profile-form" enctype="multipart/form-data">
      <fieldset>
         <div class="setting-profile-alert setting-update-alert"></div>
          <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="facebook"><?php echo $wo['lang']['facebook'];?></label>  
            <div class="col-md-6">
               <input id="facebook" name="facebook" type="text" class="form-control input-md" value="<?php echo $wo['setting']['facebook'];?>" placeholder="<?php echo $wo['lang']['username'];?>">
            </div>
         </div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="twitter"><?php echo $wo['lang']['twitter'];?></label>  
            <div class="col-md-6">
               <input id="twitter" name="twitter" type="text" class="form-control input-md" value="<?php echo $wo['setting']['twitter'];?>" placeholder="<?php echo $wo['lang']['username'];?>">
            </div>
         </div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="google"><?php echo $wo['lang']['google'];?></label>
            <div class="col-md-6">
               <input id="google" name="google" type="text" class="form-control input-md" value="<?php echo $wo['setting']['google'];?>" placeholder="<?php echo $wo['lang']['username'];?>">
            </div>
         </div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="vk"><?php echo $wo['lang']['vkontakte'];?></label>
            <div class="col-md-6">
               <input id="google" name="vk" type="text" class="form-control input-md" value="<?php echo $wo['setting']['vk'];?>" placeholder="<?php echo $wo['lang']['username'];?>">
            </div>
         </div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="linkedin"><?php echo $wo['lang']['linkedin'];?></label>  
            <div class="col-md-6">
               <input id="linkedin" name="linkedin" type="text" class="form-control input-md" value="<?php echo $wo['setting']['linkedin'];?>" placeholder="<?php echo $wo['lang']['username'];?>"> 
            </div>
         </div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-2" for="youtube"><?php echo $wo['lang']['youtube'];?></label>  
            <div class="col-md-6">
               <input id="youtube" name="youtube" type="text" class="form-control input-md" value="<?php echo $wo['setting']['youtube'];?>" placeholder="<?php echo $wo['lang']['username'];?>"> 
            </div>
         </div>
         <hr>
         <div class="form-group last-btn">
            <label class="col-md-2"></label>  
            <div class="col-sm-3">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i> <?php echo $wo['lang']['save']; ?>
               </button>
            </div>
         </div>
         <input type="hidden" name="page_id" id="page-id" value="<?php echo $wo['setting']['page_id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
      </fieldset>
   </form>
</div>
</div>

<script type="text/javascript">
$(function() {
  $('form.setting-profile-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=pages&s=update_sociallink_setting',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-profile-form').find('button'));
    },
    success: function(data) {
      if (data.status == 200) {
        scrollToTop();
        $('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      } 
      Wo_progressIconLoader($('form.setting-profile-form').find('button'));
    }
  });
});
</script>