<?php 
$not_found = '<h5 class="search-filter-center-text"><i class="fa fa-exclamation-circle"></i> ' . $wo["lang"]["no_result"] . '</h5>';
$type_to_find = '<h5 class="search-filter-center-text"> ' . $wo["lang"]["what_are_looking_for"] . '</h5>';
?>
<div class="page-margin">
   <div class="row">
      <div class="col-md-8">
         <div class="list-group">
            <div class="list-group-item"><i class="fa fa-bars"></i> <?php echo $wo['lang']['result'];?></div>
            <div class="setting-well">
               <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#users" style="height: 35px;"><i class="fa fa-user"></i> <?php echo $wo['lang']['users'];?></a></li>
                  <?php if ($wo['config']['pages'] == 1) { ?><li><a data-toggle="tab" href="#pages" style="height: 35px;"><i class="fa fa-flag"></i> <?php echo $wo['lang']['pages'];?></a></li><?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?><li><a data-toggle="tab" href="#groups" style="height: 35px;"><i class="fa fa-users"></i> <?php echo $wo['lang']['groups'];?></a></li><?php } ?>
                  <?php if ($wo['config']['games'] == 1) { ?><li><a data-toggle="tab" href="#games" style="height: 35px;"><i class="fa fa-gamepad"></i> <?php echo $wo['lang']['games'];?></a></li><?php } ?>
               </ul>
               <div class="tab-content">
                  <div id="users" class="tab-pane fade in active">
                  <div id="users-cont">

                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchFilter($_GET, 30);
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br>
                    <div class="load-more">
                        <button class="btn btn-default text-center pointer load-more-users">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_users'] ?>
                        </button>
                    </div>
                  </div>
                  <?php if ($wo['config']['pages'] == 1) { ?>
                  <div id="pages" class="tab-pane fade">
                    <div id="pages-cont">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'pages');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br>
                    <div class="load-more">
                        <button class="btn btn-default text-center pointer load-more-pages">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_pages'] ?>
                        </button>
                    </div>
                  </div>
                  <?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?>
                  <div id="groups" class="tab-pane fade">
                    <div id="groups-cont">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'groups');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br> 
                    <div class="load-more">
                        <button class="btn btn-default text-center pointer load-more-groups">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_groups'] ?>
                        </button>
                    </div>
                  </div>
                  <?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?>
                  <div id="games" class="tab-pane fade">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'games');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['game']) {
                                  echo Wo_LoadPage('games/game-list');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>

                  </div>
                  <?php } ?>
               </div>
            </div>
            <div class="clear"></div>
         </div>
      </div>
      <div class="col-md-4">
        <div class="list-group">
            <div class="list-group-item"><i class="fa fa-search"></i> <?php echo $wo['lang']['search_filter'];?></div>
            <div class="setting-well">
         <form action="#" method="get" class="search-filter-form">
            <h5><?php echo $wo['lang']['keyword'];?></h5>
            <div class="form-group">
               <input type="text" name="query" id="query" class="form-control" value="<?php echo (isset($_GET['query'])) ? Wo_Secure($_GET['query']): '';?>" autocomplete="off">
            </div>
            <h5><?php echo $wo['lang']['country'];?></h5>
            <div class="form-group">
               <select name="country" id="country" class="form-control">
                  <option value="all" selected><?php echo $wo['lang']['all'];?></option>
                  <?php 
                  foreach ($wo['countries_name'] as $country_ids => $country) { 
                  $selected_c = (!empty($_GET['country']) && $_GET['country'] == $country_ids) ? ' selected': '';
                  ?>
                  <option value="<?php echo $country_ids;?>" <?php echo $selected_c?>><?php echo $country;?></option>
                  <?php } ?>
               </select>
            </div>
          <div class="form-group">
             <?php 
             $selected_status_all = 'checked';
             $selected_status_on = '';
             $selected_status_off = '';
             if (!empty($_GET['status'])) {
                if ($_GET['status'] == 'on') {
                  $selected_status_on = 'checked';
                  $selected_status_all = '';
                } else if ($_GET['status'] == 'off') {
                  $selected_status_off = 'checked';
                  $selected_status_all = '';
                } 
             }
             ?>
             <h5><?php echo $wo['lang']['status'];?></h5>
               <label class="radio-inline" for="status-0">
               <input type="radio" name="status" id="status-0" value="all" <?php echo $selected_status_all;?>>
                <?php echo $wo['lang']['all']; ?>
               </label> 
               <label class="radio-inline" for="status-1">
               <input type="radio" name="status" id="status-1" value="on" <?php echo $selected_status_on;?>>
               <?php echo $wo['lang']['online']; ?>
               </label>
               <label class="radio-inline" for="status-2">
               <input type="radio" name="status" id="status-2" value="off"<?php echo $selected_status_off;?>>
               <?php echo $wo['lang']['offline']; ?>
               </label>
            <div class="clear"></div>
         </div>

          <div class="form-group">
             <?php 
             $selected_status_all_sex = 'checked';
             $selected_status_male = '';
             $selected_status_female = '';
             if (!empty($_GET['gender'])) {
                if ($_GET['gender'] == 'male') {
                  $selected_status_male = 'checked';
                  $selected_status_all = '';
                } else if ($_GET['gender'] == 'female') {
                  $selected_status_female = 'checked';
                  $selected_status_all = '';
                } 
             }
             ?>
             <h5><?php echo $wo['lang']['gender'];?></h5>
               <label class="radio-inline" for="gender-0">
               <input type="radio" name="gender" id="gender-0" value="all" <?php echo $selected_status_all_sex;?>>
                <?php echo $wo['lang']['all']; ?>
               </label> 
               <label class="radio-inline" for="gender-1">
               <input type="radio" name="gender" id="gender-1" value="male" <?php echo $selected_status_male;?>>
               <?php echo $wo['lang']['male']; ?>
               </label>
               <label class="radio-inline" for="gender-2">
               <input type="radio" name="gender" id="gender-2" value="female" <?php echo $selected_status_female;?>>
               <?php echo $wo['lang']['female']; ?>
               </label>
            <div class="clear"></div>
         </div>
         <div class="form-group">
             <?php 
             $selected_status_image_all = 'checked';
             $selected_status_image_y = '';
             $selected_status_image_n = '';
             if (!empty($_GET['image'])) {
                if ($_GET['image'] == 'yes') {
                  $selected_status_image_y = 'checked';
                  $selected_status_image_all = '';
                } else if ($_GET['image'] == 'no') {
                  $selected_status_image_n = 'checked';
                  $selected_status_image_all = '';
                } 
             }
             ?>
             <h5><?php echo $wo['lang']['profile_picture'];?></h5>
               <label class="radio-inline" for="image-0">
               <input type="radio" name="image" id="image-0" value="all" <?php echo $selected_status_image_all;?>>
                <?php echo $wo['lang']['all']; ?>
               </label>
               <label class="radio-inline" for="image-1">
               <input type="radio" name="image" id="image-1" value="yes" <?php echo $selected_status_image_y;?>>
               <?php echo $wo['lang']['yes']; ?>
               </label>
               <label class="radio-inline" for="image-2">
               <input type="radio" name="image" id="image-2" value="no" <?php echo $selected_status_image_n;?>>
               <?php echo $wo['lang']['no']; ?>
               </label>
            <div class="clear"></div>
         </div>
            <hr>
            <div class="form-group last-btn">
               <button type="submit" class="btn btn-main"><i class="fa fa-search"></i>  <?php echo $wo['lang']['search'];?></button>
            </div>
         </form>
         </div>
         </div>
      </div>
   </div>
</div>
<script>
  jQuery(document).ready(function($) {
    //Load more users
    $(".load-more-users").click(function(event) {

      var u_offset = ($("[data-type=user]").length > 0) ? $("[data-type=user]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-users',offset:u_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#users-cont").append(data['html'])
          }else{$(".load-more-users").remove()}
        }
      })    
    });
    //Load more groups
    $(".load-more-groups").click(function(event) {
      var g_offset = ($("[data-type=group]").length > 0) ? $("[data-type=group]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-groups',offset:g_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#groups-cont").append(data['html'])
          }else{$(".load-more-groups").remove()}
        }
      })   
    });
    //Load more pages
    $(".load-more-pages").click(function(event) {
      var p_offset = ($("[data-type=page]").length > 0) ? $("[data-type=page]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-pages',offset:p_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#pages-cont").append(data['html'])
          }else{$(".load-more-pages").remove()}
        }
      })   
    });

    
    $("#input").hover(function(event) {
      $("#input").focus()
    });

  });
</script>