<?php 
$selected_push_yes = ($wo['config']['push'] == 1) ? ' checked' : '';
$selected_push_no  = ($wo['config']['push'] == 0) ? ' checked' : '';
?>
<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-connectdevelop"></i> Push Notifications System</div>
   <div class="setting-well">
      <form action="" method="post" class="admin-site-setting form-horizontal">
        <div class="form-group">
            <label class="col-md-3" for="push">Push notifications</label>
            <div class="col-md-5"> 
               <label class="radio-inline" for="push-0">
               <input type="radio" name="push" id="push-0" value="1" <?php echo $selected_push_yes; ?>>
               <?php echo $wo['lang']['enable']; ?>
               </label> 
               <label class="radio-inline" for="push-1">
               <input type="radio" name="push" id="push-1" value="0" <?php echo $selected_push_no; ?>>
               <?php echo $wo['lang']['disable']; ?>
               </label>
            </div>
        </div>
        <hr>
         <div class="form-group">
            <label class="col-md-3" for="push_id">OneSignal App ID</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="push_id" value="<?php echo $wo['config']['push_id'];?>">
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="push_key">REST API Key</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="push_key" value="<?php echo $wo['config']['push_key'];?>"> 
            </div>
         </div>
         <hr>
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
         <div class="form-group">
            <label class="col-md-3"></label>  
            <div class="col-md-6">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i>  <?php echo $wo['lang']['save']?>
               </button> 
            </div>
         </div>
      </form>
   </div>
</div>
<script type="text/javascript">
$(function() {
    $('form.admin-site-setting').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_sms_setting',
      beforeSend: function() {
        Wo_progressIconLoader($('form.admin-site-setting').find('button'));
      },
      success: function(data) {
        if (data.status == 200) {
          $('form.admin-site-setting button').html('<i class="fa fa-check"></i> <?php echo $wo["lang"]["saved"];?>');
          setTimeout(function () {
            $('form.admin-site-setting button').html('<i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i>  <?php echo $wo["lang"]["save"]?>');
          }, 2000);
          
          Wo_progressIconLoader($('form.admin-site-setting').find('button'));

        } 
      }
    });
});
</script>