	<?php 
	$by = ( isset($_POST['by']) ? $_POST['by'] : ( isset($_GET['by']) ? $_GET['by'] : 'all' ) );
			$where = "";
			if($by != 'all'){ $where = " type='{$by}' "; } 	
			// get plans
			$plans = Ads::get_plans("", FALSE, FALSE, "id DESC", $where);	
			$task = ( isset($_POST['task']) ? $_POST['task'] : ( isset($_GET['task']) ? $_GET['task'] : '' ) );
	?>		
	<div class="row col-sm-12">
	  <div class="panel panel-default">
	
		<?php if($sub_view == ""){ ?> 
	
		<div class="panel-heading"><strong><?php echo $wo['lang']['plugin_ads_ads_plans']; ?></strong></div>
		
		<div class="panel-body"><small><?php echo $wo['lang']['plugin_ads_plan_here_list']; ?></small></div>
		
		<div class="panel-body">
				
	<div class="clearfix mb20"> <a href="index.php?link1=admin-plugins&view=ads_plans&sub_view=plan_add" class="btn btn-success"><?php echo $wo['lang']['plugin_ads_add_ads_plans']; ?></a> </div>
				 
			<ul class="nav nav-tabs">
			  <li class="<?php if($by == 'all'){ echo 'active'; }//if ?>"><a href="<?php echo $wo['config']['site_url'];?>/index.php?link1=admin-plugins&view=ads_plans&by=all"><?php echo $wo['lang']['plugin_ads_all']; ?></a></li>
			  <li class="<?php if($by == 'impression'){ echo 'active'; }//if ?>"><a href="<?php echo $wo['config']['site_url'];?>/index.php?link1=admin-plugins&view=ads_plans&by=impression"><?php echo $wo['lang']['plugin_ads_impression']; ?></a></li>
			  <li class="<?php if($by == 'clicks'){ echo 'active'; }//if ?>"><a href="<?php echo $wo['config']['site_url'];?>/index.php?link1=admin-plugins&view=ads_plans&by=clicks"><?php echo $wo['lang']['plugin_ads_clicks']; ?></a></li>
			</ul>
	<div class="row panel-body table-responsive">
			<table class="table table-striped table-bordered table-hover js_dataTable">
				<thead>
				<tr>
					<th><?php echo $wo['lang']['plugin_ads_name']; ?></th>
					<th><?php echo $wo['lang']['plugin_ads_type']; ?></th>
					<th><?php echo $wo['lang']['plugin_ads_price']; ?></th>
					<th><?php echo $wo['lang']['plugin_ads_quantity']; ?></th>
				   <?php /*  <th><?php echo $wo['lang']['plugin_ads_ads']; ?></th> */ ?>
					<th><?php echo $wo['lang']['plugin_ads_action']; ?></th>
				</tr>
				</thead>
	
				<tbody class="ads_list_content">
					
					<?php foreach($plans as $plan){ ?>
						<tr class="list_ad" data-id="<?php echo $plan['id']; ?>">
							<td><?php echo $plan['name']; ?></td>
							<td><?php echo $plan['type']; ?></td>
							<td><?php echo $plan['price']; ?></td>
							<td><?php echo $plan['quantity']; ?></td>
							<td>
		<a href="<?php echo $wo['config']['site_url'];?>/index.php?link1=admin-plugins&view=ads_plans&sub_view=plan_add&plan_id=<?php echo $plan['id']; ?>" title="<?php echo $wo['lang']['edit']; ?>"><i class="fa fa-pencil"></i></a>
		<a class="admin-delete-plan-from-list" data-id="<?php echo $plan['id']; ?>" href="#" title="<?php echo $wo['lang']['plugin_ads_delete']; ?>"><i class="fa fa-trash-o"></i></a>
							</td>
						</tr>
	                <?php } ?>					
					
				</tbody>
			</table>
	</div>
	
	
	
		</div>
	  <?php }else{ 
			$plan_id = ( isset($_POST['plan_id']) ? $_POST['plan_id'] : ( isset($_GET['plan_id']) ? $_GET['plan_id'] : 0 ) );
			//get plan
			if($plan_id != 0){ $plan = Ads::get_plan($plan_id, "");  }	else {
			   $plan = array('id' => '', 'name' => '', 'description' => '', 'type' => '', 'price' => '', 'quantity' => '' );
			}
		  ?> 
		  <div class="pull-right mt10 mr10"><a href="index.php?link1=admin-plugins&view=ads_plans"><?php echo $wo['lang']['plugin_back_to_listing']; ?></a></div>
		  <div class="panel-heading"><strong><?php echo $wo['lang']['plugin_ads_ads_plans']; ?></strong></div>
		  <div class="panel-body">
			  
			  <form class="js_ajax_forms form-horizontal" data-url="?f=admin_ads" method="post"> 
				<input type="hidden" name="task" value="plan_save"/>            
				<input type="hidden" value="<?php echo $plan['id']; ?>" class="form-control" name="plan_id"/>
				
				<div class="form-group">
					<label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_plan_title']; ?></label>
					<div class="col-sm-7">
						<input type="text" value="<?php echo $plan['name']; ?>" class="form-control" name="name"/>
						<p class="help-block"><?php echo $wo['lang']['plugin_ads_plan_unique_name']; ?></p>
					</div>
	
				</div>
	
				<div class="form-group">
					<label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_plan_desc']; ?></label>
					<div class="col-sm-7">
						<input value="<?php echo $plan['description']; ?>" type="text" class="form-control" name="description"/>
						<p class="help-block"><?php echo $wo['lang']['plugin_ads_plan_short_desc']; ?></p>
					</div>
	
				</div>
	
				<div class="form-group">
					<label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_plan_type']; ?></label>
					<div class="col-sm-7">
						<select name="type" class="form-control">                        
							<option <?php if($plan['type'] == 'impression'){ echo 'selected'; } ?> value="impression"><?php echo $wo['lang']['plugin_ads_impression']; ?></option>
							<option <?php if($plan['type'] == 'clicks'){ echo 'selected'; } ?> value="clicks"><?php echo $wo['lang']['plugin_ads_clicks']; ?></option>
							<?php /*<option <?php if($plan['type'] == 'period'){ echo 'selected'; } ?> value="period"><?php echo $wo['lang']['plugin_ads_period']; ?></option> */ ?>
						</select>
						<p class="help-block"><?php echo $wo['lang']['plugin_ads_plan_type_be']; ?></p>
					</div>
				</div>
	
				<div class="form-group">
					<label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_plan_price']; ?> </label>
					<div class="col-sm-7">
						<input value="<?php echo $plan['price']; ?>" type="text" placeholder="<?php echo $wo['lang']['plugin_ads_plan_example_30']; ?>" class="form-control" name="price"/>
						<p class="help-block"><?php echo $wo['lang']['plugin_ads_plan_price_dollar']; ?> <strong><?php echo $wo['lang']['plugin_ads_for_example_30']; ?></strong></p>
					</div>
				</div>
				
				<div class="form-group">
					<label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_plan_quantity']; ?></label>
					<div class="col-sm-7">
						<input value="<?php echo $plan['quantity']; ?>" type="text" placeholder="<?php echo $wo['lang']['plugin_ads_plan_example_100']; ?>" class="form-control" name="quantity"/>
						<p class="help-block"><?php echo $wo['lang']['plugin_ads_plan_give_quantity']; ?>
	
							<strong><?php echo $wo['lang']['plugin_ads_like_clicks_imp']; ?></strong><?php echo $wo['lang']['plugin_ads_stop_the_ads']; ?></p>
					</div>
				</div>
				
	
				<div class="body-header">
					<button class="btn btn-danger no-radius" type="submit"><?php echo $wo['lang']['plugin_ads_plan_add']; ?></button>
				</div>
				
				<div class="row col-xs-12">
				<?php /* success */ ?>
				<div class="alert alert-success mb0 mt10 x-hidden" role="alert"></div>
				<?php /* ssuccess */ ?>
				<?php /* serror */ ?>
				<div class="alert alert-danger mb0 mt10 x-hidden" role="alert"></div>
				<?php /* serror */ ?>
				</div>	
				
			</form>
		  </div>
	  <?php } ?> 
	
	  
	  </div>
	</div>
