<div class="panel panel-default">
    <div class="panel-heading with-icon">
		<i class="fa fa-plug pr5 panel-icon"></i><strong> <?php echo $wo['lang']['plugin_plugin_list']; ?></strong>
	</div>
</div>

	    
<?php if($plugins_installed['count'] == 0 && $plugins_ready['count'] == 0){ ?>
<div class="panel panel-default">
    <div class="panel-body">
		<div class="alert alert-warning"><i class="fa fa-exclamation-triangle fa-lg"></i> <?php echo $wo['lang']['plugin_no_plugins_available']; ?> </div>
	</div>
</div>
<?php } else { ?>		
	<?php foreach($plugins_installed['plugins'] as $plugin){ ?>
		<div class="panel panel-default clearfix">
			<div class="panel-heading with-icon">
				<strong><?php echo $plugin['p_name']; ?> <?php echo $plugin['p_version']; ?></strong>
			</div>
			<div class="panel-body">
									
				<form class="js_ajax_forms form-horizontal" data-url="?f=admin_plugins" action="<?php echo $wo['confi']['site_url']; ?>/plugin_requests.php?f=admin_plugins" method="post">						
					<input type="hidden" name="task" value="plugin">
					<input type="hidden" name="p_id" value="<?php echo $plugin['p_id']; ?>">
					<div class="col-sm-7">
						<div style="font-size:13px;"><?php echo $plugin['p_desc']; ?> <span class="caret pointer" onclick="$(this).closest('.panel').find('.p_more_info').toggleClass('x-hidden')"></span></div>
						<div class="mt10 p_more_info x-hidden">
							<input type="text" name="p_key" class="form-control" value="<?php echo $plugin['p_key']; ?>" placeholder="Add you key code">
						</div>
					</div>
					<div class="col-sm-2">				 
						 <input type="checkbox" name="p_active" data-toggle="toggle" data-onstyle="success" data-style="ios" data-offstyle="danger" id="p_active_<?php echo $plugin['p_id']; ?>" <?php if($plugin['p_active'] == '1'){ echo 'checked'; } ?> >						 
					</div>	
					<div class="col-sm-2">
						<button type="submit" class="btn btn-primary">
							<i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i> <?php echo $wo['lang']['plugin_save_changes']; ?>
						</button>
					</div>	
					<div class="row col-xs-12">
						<?php /* success */ ?>
						<div class="alert alert-success mb0 mt10 x-hidden" role="alert"></div>
						<?php /* serror */ ?>
						<div class="alert alert-danger mb0 mt10 x-hidden" role="alert"></div>
					</div>	
					
				</form>
			</div>
		</div>
	<?php } ?>	

<?php } //IF ?>