<?php global $sqlConnect;
                $id = ( isset($_POST['sub_view']) ? $_POST['sub_view'] : ( isset($_GET['sub_view']) ? $_GET['sub_view'] : '' ) );
				
				$sql =  " SELECT 
				          W.*, S.title, S.body, S.cost, S.cant, 
						  S.enabled, S.transact_state, U.user_id, U.username, U.first_name, U.last_name, U.gender, U.avatar, U.user_invitesleft 
						  FROM userpointspender_users AS W
						  LEFT JOIN 
						       userpointspender AS S ON W.offer = S.id
						  LEFT JOIN 
							   Wo_Users AS U ON W.user_id = U.user_id ";
				
					if( $id > 0) { $sql .=  " WHERE W.id='{$id}' LIMIT 1 "; } 
				
				   $resource = $sqlConnect->query( $sql );
				   $total_rows =  $resource->num_rows;
				
				   $rows = array();
				   while($row = $resource->fetch_assoc()) {
				      if($row['avatar']!= ''){ $row['user_picture'] =  $row['avatar']; } else { $row['user_picture'] = 'upload/photos/d-avatar.jpg'; }
					  if($row['first_name']!= ''){ $row['user_fullname'] =  $row['first_name'].' '.$row['last_name']; } else { $row['user_fullname'] = $row['username']; }
				      $rows[] = $row;
				   }

					if( $id > 0) { $rows = $rows[0]; } 
?>
<div class="row col-sm-12">
<?php if($sub_view == ""){ ?>
    <div class="panel panel-default">
    <div class="panel-heading"><strong><?php echo $wo['lang']['plugin_point_view_list_shop']; ?></strong></div>
    <div class="panel-body">
                           <small><?php echo $wo['lang']['plugin_point_view_list_shop_desc']; ?>.</small>
		 
		<div class="row panel-body with-table">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover js_dataTable">
                    <thead>
                        <tr>
                            <th><?php echo $wo['lang']['plugin_point_id']; ?></th>
                            <th><?php echo $wo['lang']['plugin_point_user']; ?></th>
							<th><?php echo $wo['lang']['plugin_point_item']; ?></th>	
							<th><?php echo $wo['lang']['plugin_point_status']; ?></th>							
                            <th><?php echo $wo['lang']['plugin_point_date']; ?></th>
                            <th><?php echo $wo['lang']['plugin_point_options']; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($rows as $row){ ?>
                        <tr>
                            <td><?php echo $row['id']; //|regex_replace:"/&#039;/":"'"|truncate:16:"..":true ?></td>
                            <td><a target="_blank" class="x-image sm" href="<?php echo $wo['config']['site_url']; ?>/<?php echo $row['username']; ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $row['user_fullname']; ?>" style="background-image:url(<?php echo $wo['config']['site_url']; ?>/<?php echo $row['avatar']; ?>);">
                                </a></td>
							<td><?php echo $row['title']; ?></td>
							<td><?php if($row['status'] == 0){ ?>
                                <span class="label label-success"><?php echo $wo['lang']['plugin_point_completed']; ?></span>
                                <?php }else{ ?>
                                <span class="label label-danger"><?php echo $wo['lang']['plugin_point_pending']; ?></span>
                                <?php } ?></td>
                            <td><?php echo date('Y-m-d H:i:s', $row['stamp']) ?></td>
                            <td>
                                
                                <button class="btn btn-xs btn-danger shop_delete_user" data-handle="point_shop_users" data-id="<?php echo $row['id']; ?>">
                                    <i class="fa fa-trash-o"></i>
                                </button>
                                <a href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=admin-plugins&view=points_shop_users&sub_view=<?php echo $row['id']; ?>" class="btn btn-xs btn-primary">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            </td>
                        </tr>
                        <?php }//F ?>
                    </tbody>
                </table>
            </div>
        </div>
		
		
    </div>
</div>
<?php }else{ ?>
            <div class="pull-right mt10 mr10"><a href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=admin-plugins&view=points_shop_users"><?php echo $wo['lang']['plugin_back_to_listing']; ?></a></div>
			
<div class="panel panel-default">
    <div class="panel-heading"><strong><?php echo $wo['lang']['plugin_point_item_of']; ?> <?php echo $rows['user_fullname']; ?></strong></div>
	        
			
         <div class="panel-body">

     <form class="js_form form-horizontal" data-url="?f=admin_points" action="<?php echo $wo['config']['site_url']; ?>/plugin_requests.php?f=admin_points" method="post">
	                       
		   <div class="row">
                <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-4 mb10">
				    <a href="<?php echo $wo['config']['site_url'].'/'.$rows['username']; ?>">
						<img class="img-responsive img-thumbnail" src="<?php echo $rows['user_picture']; ?>">
					</a>
                </div>
                <div class="col-xs-12 col-sm-8 mb10">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="badge"><?php echo $rows['user_id']; ?></span>
                            <?php echo $wo['lang']['plugin_point_user_id']; ?>
                        </li>
						<li class="list-group-item">
                            <span class="badge"><?php echo $rows['user_invitesleft']; ?></span>
                            <?php echo $wo['lang']['plugin_point_invites_of_user']; ?>
                        </li>
                        <li class="list-group-item">
                            <span class="badge"><?php echo date('Y-m-d H:i:s', $rows['stamp']); ?></span>
                            <?php echo $wo['lang']['plugin_point_purchase_time']; ?>
                        </li>						
						<li class="list-group-item">
                            <span class="badge"><?php echo $rows['cost']; ?></span>
                            <?php echo $wo['lang']['plugin_point_cost']; ?>
                        </li>
                    </ul>
                </div>				
            </div>
			
			 <div class="row">

                <div class="col-xs-12 col-sm-4 mb10">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong><?php echo $wo['lang']['plugin_point_title']; ?>:</strong>
                        </li>
						<li class="list-group-item">
                            <?php echo $rows['title']; ?>
                        </li>
                    </ul>
                </div>	
				
				<div class="col-xs-12 col-sm-8 mb10">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong><?php echo $wo['lang']['plugin_point_desc']; ?>:</strong>
                        </li>
						<li class="list-group-item">
                            <?php echo $rows['body']; ?>
                        </li>
                    </ul>
                </div>	
							
            </div>			   
						    													
			<div class="form-group">
				<label class="col-sm-4"><?php echo $wo['lang']['plugin_point_add_invitations']; ?>:</label>
				<div class="col-sm-8">
				<input type="text" class="form-control" name="news_invites" value="0" size="40" maxlength="250">
				</div>
			</div>	
										
			<div class="form-group <?php if($rows['state'] == 0){ ?> SELECTED<?php } ?>">
				<label class="col-sm-4"><?php echo $wo['lang']['plugin_point_complete_transaction']; ?>:</label>
				<div class="col-sm-8">
				<select class="form-control" name="status">
					 <option value="0"<?php if($rows['status'] == 0){ ?> SELECTED<?php } ?>><?php echo $wo['lang']['plugin_point_completed']; ?></option>
					 <option value="1"<?php if($rows['status'] == 1){ ?> SELECTED<?php } ?>><?php echo $wo['lang']['plugin_point_pending']; ?></option>
				</select>
				</div>
			</div>	

            <div class="body-header">
				<button class="btn btn-success no_radius js_btn" type="submit"><?php echo $wo['lang']['plugin_point_save']; ?></button>
            </div>

            <div class="row col-xs-12">
			<?php /* success */ ?>
            <div class="alert alert-success mb0 mt10 x-hidden" role="alert"></div>
            <?php /* success */ ?>
            <?php /* error */ ?>
            <div class="alert alert-danger mb0 mt10 x-hidden" role="alert"></div>
            <?php /* error */ ?>
			</div>	

			<input type="hidden" name="task" value="shop_user_edit">
			<input type="hidden" name="item_id" value="<?php echo $rows['id']; ?>">
			<input type="hidden" name="user_id" value="<?php echo $rows['user_id']; ?>">
			<input type="hidden" name="transaction_id" value="<?php echo $rows['transaction_id']; ?>">
	</form>
 
         </div>
</div>						   
<?php } ?>
</div>