<?php
	global $sqlConnect;
	$ads = array(); 
	$resource = $sqlConnect->query("SELECT * FROM ads_reports");
	if($resource->num_rows>0){
		while($row = $resource->fetch_assoc()){
			$ads[] = $row;
		}
	}
	if($sub_view == ""){ 
?>
   	<div class="panel panel-default"> 
		<div class="panel-heading"><strong>Advertising Campaigns</strong></div>
		<div class="panel-body"><small>Here you can view reports of ads, report link, report image, bug.</small></div>	
		<div class="panel-body">

			<div class="row panel-body table-responsive">
					<table class="table table-striped table-bordered table-hover js_dataTable">
						<thead>
							<tr>
								<th>id</th>
								<th>ads reported</th>
								<th>report type</th>
								<th>user_id</th>
								<th>time</th>
								<th><?php echo $wo['lang']['plugin_ads_action']; ?></th>
							</tr>
						</thead>
			
						<tbody class="ads_list_content">
							   
							<?php foreach($ads as $ad){ ?>
								<tr class="list_ad" data-id="<?php echo $ad['report_id']; ?>">
								<td><?php echo $ad['report_id']; ?></td>
								<td><?php echo $ad['report_ad_id']; ?></td>
								<td><?php echo $ad['report_user_id']; ?></td>
								<td><?php echo $ad['report_time']; ?></td>
								<td>
									<a href="<?php echo $wo['config']['site_url'];?>/index.php?link1=admin-plugins&view=view_campaigns&sub_view=edit&ad_id=<?php echo $ad['report_ad_id']; ?>" title="<?php echo $wo['lang']['edit']; ?>"><i class="fa fa-pencil"></i></a>
									<a class="admin-delete-ads-from-list" data-id="<?php echo $ad['report_id']; ?>" href="#" title="<?php echo $wo['lang']['plugin_ads_delete']; ?>"><i class="fa fa-trash-o"></i></a>
								</td>
								</tr>
							<?php }//f ?>					   
					   
						</tbody>
				</table>
			</div>


    </div>
	</div>
 <?php }else{    
        global $sqlConnect;
        $ad_id = ( isset($_POST['ad_id']) ? $_POST['ad_id'] : ( isset($_GET['ad_id']) ? $_GET['ad_id'] : 0 ) );
		//get ad
		if($ad_id != 0){ $ad = Ads::get_ad($ad_id, "");  }	

		$resource = $sqlConnect->query("SELECT user_id, username, first_name, last_name, gender, avatar FROM Wo_Users WHERE user_id='{$ad['user_id']}' LIMIT 1");	
		$rows = $resource->fetch_assoc(); 
		if($rows['avatar']!= ''){ $rows['user_picture'] =  $rows['avatar']; } else { $rows['user_picture'] = 'upload/photos/d-avatar.jpg'; }
		if($rows['first_name']!= ''){ $rows['user_fullname'] =  $rows['first_name'].' '.$rows['last_name']; } else { $rows['user_fullname'] = $rows['username']; }	   
		$where = " type='{$ad['plan_type']}' ";      	
	    
		// get plans
		$plans = Ads::get_plans("", FALSE, FALSE, "id DESC", $where);		
?>      
<div class="panel panel-default"> 
<div class="panel-heading"><strong><?php echo $wo['lang']['plugin_ads_edit_ad']; ?> - <?php echo $rows['user_fullname']; ?></strong></div>
        <div class="panel-body">
           
		   <div class="row">
                <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-2 mb10">
                    <img class="img-responsive img-thumbnail" src="<?php echo $rows['user_picture']; ?>">
                </div>
                <div class="col-xs-12 col-sm-10 mb10">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="badge"><?php echo $rows['user_id']; ?></span>
                            <?php echo $wo['lang']['plugin_tab_user_id']; ?>
                        </li>
                        <li class="list-group-item">
                            <span class="badge"><?php echo $ad['created']; ?></span>
                            <?php echo $wo['lang']['plugin_ads_ads_time_created']; ?>
                        </li>
						<li class="list-group-item">
                            <span class="badge"><?php echo $ad['updated']; ?></span>
                            <?php echo $wo['lang']['plugin_ads_ads_time_updated']; ?>
                        </li>						
                    </ul>
                </div>				
            </div>
        
		<form class="js_ajax_forms form-horizontal" data-url="?f=admin_ads" method="post"> 
		    <input type="hidden" name="task" value="save_ad_edit">  
		    <input type="hidden" id="ads-id" value="<?php echo $ad['id']; ?>" class="form-control" name="ad_id">
            
			<div class="form-group mb20">
			    <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_image']; ?></label>
				<div class="col-sm-7">
			        <?php if(!empty($ad['images'])){ ?><img src="<?php echo $ad['images']; ?>" style="max-width:200px; width:100%;"><?php } ?>
				</div>
			</div>
			
			<div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_ad_camp_name']; ?></label>
                <div class="col-sm-7">
                    <input type="text" value="<?php echo $ad['campaign_name']; ?>" class="form-control" name="campaign_name">
                </div>
            </div>
						
			<div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_link']; ?></label>
                <div class="col-sm-7">
                    <input type="text" value="<?php echo $ad['link']; ?>" class="form-control" name="link">
                </div>
            </div>
			
			<div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_title']; ?></label>
                <div class="col-sm-7">
                    <input type="text" value="<?php echo $ad['title']; ?>" class="form-control" name="title">
                </div>
            </div>
			
			<div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_desc']; ?></label>
                <div class="col-sm-7">
                    <input type="text" value="<?php echo $ad['description']; ?>" class="form-control" name="description">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_optimize_for']; ?></label>
                <div class="col-sm-7">
                    <div class="alert alert-danger">
                        <strong><?php echo $wo['lang']['plugin_ads_note']; ?>:</strong> <?php echo $wo['lang']['plugin_ads_note_change_plan']; ?>
                    </div>
                    <select  style="width: 60%" class="form-control ads-plan-type" name="plan_type">
                        <option <?php if($ad['plan_type'] == 'clicks'){ echo 'selected'; } ?> value="clicks"><?php echo $wo['lang']['plugin_ads_clicks']; ?></option>
                        <option <?php if($ad['plan_type'] == 'impression'){ echo 'selected'; } ?> value="impression"><?php echo $wo['lang']['plugin_ads_impressions']; ?></option>
                    </select>
                </div>
            </div>
			
            <div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_how_much_to_spend']; ?></label>
                <div class="col-sm-7">
                    <select  style="width: 60%" class="form-control ads-plans" name="plan_id">
                        <?php foreach($plans as $plan){ ?>
                        <option <?php if($ad['plan_id'] == $plan['id']){ echo 'selected'; } ?> value="<?php echo $plan['id']; ?>"><?php echo $plan['name']; ?> ($<?php echo $plan['price']; ?>)</option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4"><?php echo $wo['lang']['plugin_ads_ad_status']; ?></label>
                <div class="col-sm-7">
                    <select style="width: 60%" name="status" class="form-control">
                        <option <?php if($ad['status'] == '1'){ echo 'selected'; } ?> value="1"><?php echo $wo['lang']['plugin_ads_ad_running']; ?></option>
                        <option <?php if($ad['status'] == '0'){ echo 'selected'; } ?> value="0"><?php echo $wo['lang']['plugin_ads_ad_stopped']; ?></option>
                    </select>
                </div>
            </div>
			
            <div class="body-header mb10">
				<button class="btn btn-danger no-radius" type="submit"><?php echo $wo['lang']['plugin_ads_save_ad']; ?></button>
            </div>
			
			<div class="row col-xs-12">
				<?php /* success */ ?>
				<div class="alert alert-success mb0 mt10 x-hidden" role="alert"></div>
				<?php /* ssuccess */ ?>
				<?php /* serror */ ?>
				<div class="alert alert-danger mb0 mt10 x-hidden" role="alert"></div>
				<?php /* serror */ ?>
		    </div>
			
        </form>
      </div>
</div>	  
 <?php } ?>