<?php if ($wo['loggedin'] == true) { ?>
<div class="left-sidebar">
	<ul>
		<li><a href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-01.png"/> <?php echo $wo['lang']['my_profile'];?></a></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=messages'); ?>" data-ajax="?link1=messages"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-02.png"/> <?php echo $wo['lang']['messages'];?></a></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=setting'); ?>" data-ajax="?link1=setting"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-03.png"/> <?php echo $wo['lang']['setting'];?></a></li>
		<li><hr></li>
		<?php if (Wo_CanBlog() == true) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" data-ajax="?link1=my-blogs"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-04.png"/> <?php echo $wo['lang']['my_articles'] ?></a></li>
		<?php } ?>
		<?php if ($wo['config']['groups'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>" data-ajax="?link1=groups"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-05.png"/> <?php echo $wo['lang']['groups'];?></a></li><?php } ?>
		<?php if ($wo['config']['pages'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-06.png"/> <?php echo $wo['lang']['pages'];?></a></li><?php } ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-07.png"/> <?php echo $wo['lang']['albums'];?></a></li>
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-08.png"/> <?php echo $wo['lang']['my_products'];?></a></li>
		<?php } ?>
        <li><hr></li>
		<?php if ($wo['config']['games'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=games'); ?>" data-ajax="?link1=games"><i class="fa fa-gamepad fa-fw"></i><?php echo $wo['lang']['games'];?></a></li><?php } ?>
		<li><hr></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>" data-ajax="?link1=saved-posts"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-09.png"/> <?php echo $wo['lang']['saved_posts'];?></a></li>
		<?php if ($wo['config']['blogs'] == 1) { ?>
		<li><hr></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-10.png"/> <?php echo $wo['lang']['blog'] ?></a></li>
		<?php } ?>
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>"><img class="icon-cate" src="<?php echo $wo['config']['theme_url'];?>/img/icon-menu/cate-left-11.png"/> <?php echo $wo['lang']['market'];?></a></li>
		<?php } ?>
		<li><hr></li>
		<?php if ($wo['user']['is_pro'] == 0 && $wo['config']['pro'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>"><i class="fa fa-arrow-down fa-fw"></i><?php echo $wo['lang']['put_me_here'];?></a></li>
		<?php } ?>
		<?php /* plugin menu */ ?>
				<?php if(!empty($wo['plugin_list']['plugin_menu'])){ ?>
					<li><hr></li>				
					<?php echo Wo_LoadPage('plugins/plugin_menu'); /* plugin menu */ ?>	
				<?php } ?>	
		<li><hr></li>
		<?php if ($wo['user']['is_pro'] == 0 && $wo['config']['pro'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>"><i class="fa fa-arrow-down fa-fw"></i><?php echo $wo['lang']['put_me_here'];?></a></li>
		<?php } ?>
	</ul>
	<?php if ($wo['config']['pro'] == 1) { ?>
      <div class="featured-users">
        <ul class="list-inline">
          <?php 
          $users = Wo_FeaturedUsers(9);
          ?>
          <?php 
          foreach ($users as $wo['user-list']) {
              echo Wo_LoadPage('home/user-list');
          }
          ?>
        </ul>
      </div><br>
      <?php } ?>
</div>
<?php } ?>