<span id="join-<?php echo $wo['join']['id']?>">
    <button type="button" onclick="Wo_RegisterGroupJoin(<?php echo $wo['join']['id'];?>, <?php echo ($wo['join']['join_privacy'] == 2) ? 1 : 0;?>)" class="btn-requested btn btn-default btn-sm">
       <i class="fa fa-clock-o progress-icon" data-icon="clock-o"></i>
       <span class="button-text"> <?php echo $wo['lang']['requested'];?></span>
    </button>
</span>