<style>
	.navbar-forum {
		background-color: #fff;
		margin-top: 25px;
		height: 45px;
	}
	.f_category,.member_list,.adv-mbr-search,.g_search, .bg-main, .blocksubhead  {
		background-color: #4caf50;
		color: #fff;
	}
	.section-list {
		padding: 10px;
	}
	.forum-tabs{
		width: 100%;
		overflow: hidden;
		margin-bottom: 20px;
	}
	.forum-tabs li{
		width: 25%;
		background-color: #a84849;
		float: left;
		text-align: center;
		font-size: 14px;
	}
	.forum-tabs li a{
		width: 100%;
		padding: 10px 0px;
		background-color: #a84849;
		color: #fff;
		vertical-align: middle;
	}
	.forum-tabs li a:hover{
		background: rgba(245, 245, 245, 0.04);
	}
    .navbar-forum .navbar-nav>.active>a, .navbar-forum .navbar-nav>.active>a:focus, .navbar-forum .navbar-nav>.active>a:hover, .nav-names li:hover{
    	color: #03A9F4 !important;
    background-color: #ffffff !important;
    border-color: #03A9F4 !important;
    border-bottom: 3px solid;
    font-weight: bold;
    }
    .navbar-collapse {
    	padding-left: 0 !important;
    }
    .flink {
    	color: <?php echo $wo['config']['btn_background_color'];?> !important;
    }
    blockquote {
	    border-left: 2px solid <?php echo $wo['config']['btn_background_color'];?> !important;
    }
    .bbcode-editor .bbcode-toolbar {
      color: #fff;
      background: #03A9F4 !important;
      padding: 8px;
    }

</style>
<?php 
$forum_class = 'search-forums';
if (!empty($_GET['fid'])) {
	$forum_class = 'search-forum-threads';
}
if ($_GET['link1'] == 'showthread') {
	$forum_class = 'forum-messages-search';
}

 ?>
<nav class="navbar navbar-default navbar-forum" role="navigation">
  <div class="collapse navbar-collapse no-padding-right no-padding-left" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="<?php if ($wo['active'] == 'forums') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum');?>"><i class="fa fa-home"></i>  <span><?php echo $wo['lang']['forum']; ?></span></a></li>
      <li class="<?php if ($wo['active'] == 'members') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum-members');?>"><i class="fa fa-users"></i>  <span><?php echo $wo['lang']['members']; ?></span></a></li>
      <li class="<?php if ($wo['active'] == 'search') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum-search');?>"><i class="fa fa-search"></i>  <span><?php echo $wo['lang']['search']; ?></span></a></li>
    </ul>
    <ul class="nav navbar-nav <?php echo Wo_RightToLeft('pull-right') ?>">
      <li class="<?php if ($_GET['link1'] == 'mythreads') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=mythreads');?>"><i class="fa fa-book" aria-hidden="true"></i> <span><?php echo $wo['lang']['my_threads']; ?></span></a></li>
      <li class="<?php if ($_GET['link1'] == 'mymessages') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=mymessages');?>"><i class="fa fa-comments" aria-hidden="true"></i>  <span><?php echo $wo['lang']['my_messages']; ?></span></a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div class="page-margin" id="forum-cont">
	<!-- Tab panes -->
	<div class="tab-content" id="tab-content">