<div class="page-margin">

  <div class="row">

    <div class="col-md-8">
    
    <div class="wowonder-well">
    <span style="font-size:21px;">App development</span>
    <hr>
    <p>WoWonder is the fastest growing internet site in World. It accounts for over half of Russian-speaking traffic in the world. If you want to develop social games and apps, you are welcome to join in our success and get access to more than 170 million users.</p>
    <br>

    <a href="<?php echo Wo_SeoLink('index.php?link1=create-app');?>" class="btn btn-main ">Create an app</a>  <a href="<?php echo Wo_SeoLink('index.php?link1=apps');?>">Go to my apps <i class="fa fa-long-arrow-right"></i></a>
    </div>
      
    </div> <!-- .col-md-8 -->

    <div class="col-lg-4">
    	<div class="wowonder-well">
    <span style="font-size:21px;color:#a84849">Platform status</span>
    <hr>
    <span style="float:left; margin-right:10px; font-size:40px; color:#589ddd"><i class="fa fa-clock-o"></i></span>
    <div style="font-size:16px;">
    <div style="margin-top:20px; color:#589ddd">60 ms</div>
    <div style="font-size:12px; color:#888">Average response time</div>
    </div>
    <div class="clear"></div>
    <hr>
    <span style="float:left; margin-right:10px; font-size:40px; color:#589ddd"><i class="fa fa-hourglass-start"></i></span>
    <div style="font-size:16px;">
    <div style="margin-top:20px; color:#589ddd">100%</div>
    <div style="font-size:12px; color:#888">Uptime</div>
    </div>
    
    </div>
    </div>

  </div> <!-- .row -->

</div> <!-- .page-margin -->