<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-desktop"></i> <?php echo $wo['lang']['themes']; ?></div>
   <div class="setting-well">
   <form action="#" method="post" class="setting-themes-container">
      <div class="row">
         <?php
         foreach (Wo_GetThemes() as $theme_url) {
            include($theme_url . '/info.php');
            $theme = str_replace('themes/', '', $theme_url);
         ?>
         <div class="col-lg-6">
            <div class="theme <?php echo ($theme == $wo['config']['theme']) ? ' active' : '';?>">
               <img src="<?php echo $themeImg;?>" alt="">
               <div class="themeName"><?php echo $themeName;?></div>
               <div class="themeVirsion"><?php echo $wo['lang']['version'];?> <?php echo $themeVirsion;?></div>
               <div class="themeAuthor"><?php echo $wo['lang']['author'];?> <a href="<?php echo $themeAuthorUrl;?>"><?php echo $themeAuthor;?></a></div>
               <?php if($theme == $wo['config']['theme']) { ?>
               <div class="active"><i class="fa fa-check"></i> <?php echo $wo['lang']['activeted'];?></div>
               <?php } else { ?>
               <div class="active"><a href="#" id="active"><?php echo $wo['lang']['active'];?></a></div>
               <input type="hidden" name="theme" value="<?php echo $theme; ?>" />
               <?php } ?>
               <div class="clear"></div>
            </div>
         </div>
         <?php } ?>
      </div>
      <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
   </form>
   </div>
</div>
<script type="text/javascript">
$(function() {
   $('a#active').click(function() {
     $('form.setting-themes-container').submit();
   });
   $('form.setting-themes-container').ajaxForm({
     url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=updateTheme',
     beforeSend: function() {
       Wo_progressIconLoader($('form.setting-themes-container').find('button'));
     },
     success: function(data) {
       if (data.status == 200) {
         window.location = "<?php echo Wo_SeoLink('index.php?link1=admincp');?>";
       } 
       Wo_progressIconLoader($('form.setting-themes-container').find('button'));
     }
  });
});
</script>