<div class="page-margin">
   <div class="row">
      <div class="col-md-8">
        <div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-gamepad"></i> <?php echo $wo['lang']['latest_games'];?><span class="<?php echo Wo_RightToLeft('pull-right'); ?>" ><a data-ajax="?link1=games" href="<?php echo Wo_SeoLink('index.php?link1=games');?>" class=""><?php echo $wo['lang']['my_games'];?></a></span></div>
            <?php
               $games = Wo_GetAllGames(7000);
               if (count($games) > 0) {
                  foreach ($games as $wo['game']) {
                  	  $wo['game']['all'] = 1;
                      echo Wo_LoadPage('games/game-style');
                  }
               } else {
                  echo '<h5 class="search-filter-center-text no-well"> ' . $wo['lang']['no_games_found'] . '</h5>';
               }
               
               ?>
            <div class="clear"></div>
      </div>
      </div>
      <!-- .col-md-8 -->
      <?php echo Wo_LoadPage('sidebar/content');?>
   </div>
   <!-- .row -->
</div>
<script>
   function Wo_HoverOnGame(id) {
      $('#game_' + id).find('#overlay-black').addClass('overlay-black').fadeIn(200);
      $('#game_' + id).find('.game-name').fadeIn(200);
   }
   function Wo_LeaveOnGame(id) {
      $('#game_' + id).find('#overlay-black').removeClass('overlay-black').fadeOut(400);
      $('#game_' + id).find('.game-name').fadeOut(200);
   }
</script>