<div class="page-margin">
   <div class="row">
      <div class="col-md-8 profile-lists">
        <div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-users"></i> <?php echo $wo['lang']['my_groups'];?><span class="<?php echo Wo_RightToLeft('pull-right'); ?>" ><a data-ajax="?link1=create-group" href="<?php echo Wo_SeoLink('index.php?link1=create-group');?>" class=""><?php echo $wo['lang']['create']; ?></a></span></div>
   <div class="setting-well">
            <?php
               $pages = Wo_GetMyGroups();
               if (count($pages) > 0) {
                  foreach ($pages as $wo['group']) {
                      echo Wo_LoadPage('group/group-list');
                  }
               } else {
                  echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_groups_found'] . '</h5>';
               }
               
               ?>
            <div class="clear"></div>
         </div>
      </div></div>
      <!-- .col-md-8 -->
      <?php echo Wo_LoadPage('sidebar/content');?>
   </div>
   <!-- .row -->
</div>