<div class="welcome-footer">
	<a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a>
	<a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a>
   <a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a>
	<a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a>
   <?php  if ($wo['config']['blogs'] == 1) { ?><a href="<?php echo Wo_SeoLink('index.php?link1=blogs');?>"><?php echo $wo['lang']['blog'];?></a><?php } ?>
   <?php
               $pages = Wo_GetCustomPages();
               if (count($pages) > 0) {
                  foreach ($pages as $key => $page) {
                  ?>
                  <a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a>
                  <?php
                 }
               }
               ?>
	<span class="dropdown dropup">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
            <?php
               $langs = Wo_LangsNamesFromDB();
               if (count($langs) > 0) {
                   foreach ($langs as $key => $wo['langs']) {
                     $language = $wo['langs'];
                     $languages_name = ucfirst($wo['langs']);
                     $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
                ?>
               <li><a class="lang" href="<?php echo $link;?>"><?php echo $languages_name;?></a></li>
               <?php } } ?>
            </ul>
         </span>
</div>
<div class="welcome-footer-right">
	<?php 
         $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
         echo $copy = str_replace('{date}', date('Y'), $copy);
         ?>
</div>