<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-bars"></i> Custom pages</div>
   <div class="setting-well page-margin">
     <a href="<?php echo Wo_SeoLink('index.php?link1=admincp&page=add_new_page');?>" class="btn btn-main btn-sm"><i class="fa fa-plus"></i> Add new page</a><br><br>
     <p>The pages will show up in footer links.</p><br>
     <div class="table-responsive">
      <table class="table table-hover table-bordered table-condensed setting-table">
         <thead>
            <tr>
               <th><?php echo $wo['lang']['id'];?></th>
               <th>Page name</th>
               <th>Page title</th>
               <th>Type</th>
            </tr>
         </thead>
         <tbody class="posts-result manage-posts-list">
            <?php
            $fields = Wo_GetCustomPages();
            if (count($fields) > 0) {
                foreach ($fields as $key => $wo['page']) {
                    echo Wo_LoadPage('admin/custom_pages/pages');
                }
            }  
            ?>
         </tbody>
      </table>
      </div>
   </div>
</div>

<script type="text/javascript">
function Wo_DeleteCustomPage(id) {
  if (id == '') {
    return false;
  }
  if (!confirm('Are you sure you want to delete this page ?')) {
    return false;
  }
  Wo_progressIconLoader($('#' + id).find('.delete-field'));
  $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'delete_page', id:id}, function (data) {
     if (data.status == 200) {
        $('#' + id).fadeOut(300, function () {
          $(this).remove();
        });
     }
     Wo_progressIconLoader($('#' + id).find('.delete-field'));
  });
}
</script>