<div class="sidebar-conatnier">
  <div class="col-md-4">
    <ul class="list-group" id="sidebar-user-list-container">
      <li class="list-group-item text-muted" contenteditable="false">
        <i class="fa fa-users"></i> <?php echo $wo['lang']['people_you_may_want_to_meet'];?>
        </span>
      </li>
      <div class="sidebar-users-may-know-container">
        <?php 
        foreach (Wo_GetAllUsers(12, 'sidebar') as $wo['UsersList']) {
           $wo['UsersList']['user_name'] = substr($wo['UsersList']['name'],0,10);
           echo Wo_LoadPage('sidebar/sidebar-user-list');
        } 
        ?>
      </div>
      <div class="clear"></div>
    </ul>
    <ul class="list-group trending" >
      <li class="list-group-item" contenteditable="false"><i class="fa fa-bolt"></i> <?php echo $wo['lang']['trending'];?></li>
        <?php 
        $hashtags = Wa_GetTrendingHashs('popular');
        if (count($hashtags) > 0) {
          foreach ($hashtags as $wo['hashtag']) { 
        ?>
        <li class="list-group-item" dir="auto">
          <a href="<?php echo $wo['hashtag']['url'];?>">#<?php echo $wo['hashtag']['tag'];?></a>
        </li>
        <?php
          } 
        }
        ?>
      <div class="clear"></div>
    </ul>
      <?php 
      $sidebar_ad = Wo_GetAd('sidebar', false);
      if (!empty($sidebar_ad)) {?>
      <ul class="list-group sidebar-ad">
         <?php echo $sidebar_ad; ?>
      </ul>
     <?php } ?>
     <?php echo Wo_LoadPage('footer/sidebar-footer')?>
  </div>

</div>