<li>
   <span class="user-popover" data-id="<?php echo $wo['result']['id'];?>" data-type="<?php echo $wo['result']['type'];?>">
   <a href="<?php echo $wo['result']['url'] . $wo['marker'];?>ref=se" data-ajax="?link1=timeline&u=<?php echo $wo['result']['username']?>&ref=se">
      <div class="search-user-avatar <?php echo Wo_RightToLeft('pull-left');?>">
         <img src="<?php echo $wo['result']['avatar']?>" alt="<?php echo $wo['result']['name']?> Profile Picture">
      </div>
      <span class="search-user-name">
      <?php echo $wo['result']['name']?>
      <?php if(empty($wo['result']['group_id'])) {?>   
      <?php if($wo['result']['verified'] == 1) {?>   
      <span class="verified-color"><i class="fa fa-check-circle" title="<?php echo $wo['lang']['verified_user'];?>"></i
         ></span>
      <?php } ?>
      <?php } ?>
      </span>
   </a>
   </span>
   <?php if (!empty($wo['result']['page_id'])) { ?>
   <div class="user-lastseen">
      <?php echo $wo['lang']['category'];?>: <?php echo $wo['result']['category']; ?>
   </div>
   <?php } else if (!empty($wo['result']['group_id'])) { ?>
   <div class="user-lastseen">
      <?php echo $wo['lang']['members'];?>: <?php echo Wo_CountGroupMembers($wo['result']['group_id']); ?>
   </div>
   <?php } else { ?>
   <?php if($wo['config']['user_lastseen'] == 1 && $wo['result']['showlastseen'] != 0) { ?>
   <div class="user-lastseen">
      <?php echo Wo_UserStatus($wo['result']['user_id'],$wo['result']['lastseen']); ?>
   </div>
   <?php } ?>
   <?php } ?>
   <div class="clear"></div>
</li>
