<?php if ($wo['setting']['balance'] < $wo['config']['m_withdrawal']): ?>
<div class="alert alert-danger">
  <?php 
  $your_balance = str_replace('{balance}',  $wo['setting']['balance'], $wo['lang']['your_balance']); 
  $your_balance = str_replace('{m_withdrawal}',  $wo['config']['m_withdrawal'], $your_balance); 
  ?>
	<i class="fa fa-fw fa-exclamation-triangle"></i> <?php echo $your_balance;?>
</div>
<?php endif ?>
<div class="list-group">
  <div class="list-group-item"><i class="fa fa-fw fa-usd"></i> <?php echo $wo['lang']['my_balance'] ?> <?php if(Wo_IsAdmin() === true) { ?><a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>">(<?php echo $wo['setting']['name'];?>)</a><?php } ?></div>
   <div class="setting-well">
      <form class="setting-general-form form-horizontal" method="post">
      <fieldset>
         <div class="setting-general-alert setting-update-alert"></div>
         <!-- Text input-->
         <div class="form-group">
            <label class="col-md-3"></label>  
            <div class="col-md-7">
               <?php echo $wo['lang']['your_balance_is']; ?>: <b>$<?php echo $wo['setting']['balance'];?></b>
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="paypal_email"><?php echo $wo['lang']['paypal_email']; ?></label>  
            <div class="col-md-7">
               <input id="paypal_email" name="paypal_email" type="text" class="form-control input-md" value="<?php echo $wo['setting']['email']?>" autocomplete="off">
               <span class="help-block checking"></span>  
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="amount"><?php echo $wo['lang']['amount_usd']; ?></label>  
            <div class="col-md-7">
               <input name="amount" id="amount" type="text" class="form-control input-md" value="<?php echo $wo['setting']['balance'];?>">
            </div>
         </div>
         <div class="form-group last-btn">
            <label class="col-md-3"></label>
            <div class="col-sm-3">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-money progress-icon" data-icon="money"></i> <?php echo $wo['lang']['request_withdrawal']; ?>
               </button>
            </div>
         </div>
         <input type="hidden" name="user_id" value="<?php echo $wo['setting']['user_id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
      </fieldset>
   </form>
   <br>
   <hr>
   <div class="payment-history">
    <h3><?php echo $wo['lang']['payment_history']; ?></h3>
   	<div class="table-responsive">
  <table class="table table-bordered table-condensed setting-table">
    <thead>
      <tr>
        <th>#</th>
        <th><?php echo $wo['lang']['amount']; ?></th>
        <th><?php echo $wo['lang']['requested']; ?></th>
        <th><?php echo $wo['lang']['status']; ?></th>
      </tr>
    </thead>
    <tbody>
       <?php
       $get_payment = Wo_GetPaymentsHistory($wo['setting']['user_id']);
       if (count($get_payment) > 0) {
       	 foreach ($get_payment as $wo['key'] => $wo['payment']) {
       	 	$wo['key'] = ($wo['key'] + 1);
       	 	$wo['html_class'] = 'label-warning';
       	 	$wo['html_text'] = $wo['lang']['pending'];
       	 	if ($wo['payment']['status'] == 1) {
       	 		$wo['html_class'] = 'label-success';
       	 		$wo['html_text'] = $wo['lang']['approved'];
       	 	} else if ($wo['payment']['status'] == 2) {
       	 		$wo['html_class'] = 'label-danger';
       	 		$wo['html_text'] = $wo['lang']['declined'];
       	 	}
       	 	echo Wo_LoadPage('setting/payment-history');
       	 }
       }
       ?>
    </tbody>
  </table>
  </div>
   </div>
   </div>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-general-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=request_payment',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-general-form').find('button'));
    },
    success: function(data) {
      scrollToTop();
      if (data.status == 200) {
        $('.setting-general-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast');
      } else if (data.errors) {
          var errors = data.errors.join("<br>");
          $('.setting-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
          $('.alert-danger').fadeIn(300);
      }
      Wo_progressIconLoader($('form.setting-general-form').find('button'));
    }
  });
});
</script>