<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-exclamation-circle"></i> <?php echo $wo['lang']['page_information'];?> <a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['page_name'];?>">(<?php echo $wo['setting']['name'];?>)</a></div>
   <div class="setting-well">
      <form  method="post" class="form-horizontal setting-information-form">
         <fieldset>
            <div class="setting-information-alert setting-update-alert"></div>
            <!-- Text input-->
            <div class="form-group">
               <label class="col-md-2" for="page_description"><?php echo $wo['lang']['about'];?></label>
               <div class="col-md-6">
               <?php 
               $text = br2nl($wo['setting']['about']);
               ?>         
                  <textarea class="form-control" id="page_description" name="page_description" cols="20" rows="3"><?php echo $text;?></textarea>
               </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
               <label class="col-md-2" for="company"><?php echo $wo['lang']['company'];?></label>  
               <div class="col-md-6">
                  <input id="company" name="company" type="text" class="form-control input-md" value="<?php echo $wo['setting']['company'];?>">
               </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
               <label class="col-md-2" for="phone"><?php echo $wo['lang']['phone_number'];?></label>  
               <div class="col-md-6">
                  <input id="phone" name="phone" type="text" class="form-control input-md" value="<?php echo $wo['setting']['phone'];?>">
               </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
               <label class="col-md-2" for="address"><?php echo $wo['lang']['location'];?></label>  
               <div class="col-md-6">
                  <input id="address" name="address" type="text" class="form-control input-md" value="<?php echo $wo['setting']['address'];?>">
               </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
               <label class="col-md-2" for="website"><?php echo $wo['lang']['website']; ?></label>  
               <div class="col-md-6">
                  <input id="website" name="website" type="text" class="form-control input-md" value="<?php echo $wo['setting']['website'];?>">
                  <span class="help-block"><?php echo $wo['lang']['site_eg'];?></span>
               </div>
            </div>
            <div class="form-group last-btn">
               <label class="col-md-2"></label>  
               <div class="col-sm-3">
                  <button type="submit" class="btn btn-main">
                  <i class="fa fa-floppy-o progress-icon" data-icon="floppy-o"></i> <?php echo $wo['lang']['save']; ?>
                  </button>
               </div>
            </div>
            <input type="hidden" name="page_id" value="<?php echo $wo['setting']['page_id'];?>">
            <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
         </fieldset>
      </form>
   </div>
</div>
<script type="text/javascript">
   $(function() {
     $('form.setting-information-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=pages&s=update_information_setting',
       beforeSend: function() {
         Wo_progressIconLoader($('form.setting-information-form').find('button'));
       },
       success: function(data) {
         if (data.status == 200) {
           scrollToTop();
           $('.setting-information-alert').html('<div class="alert alert-success">' + data.message + '</div>');
           $('.alert-success').fadeIn('fast', function() {
             $(this).delay(2500).slideUp(500, function() {
               $(this).remove();
             });
           });
         } else {
           var errors = data.errors.join("<br>");
           scrollToTop();
           $('.setting-profile-alert').html('<div class="alert alert-danger">' + errors + '</div>');
           $('.alert-danger').fadeIn(300);
         }
         Wo_progressIconLoader($('form.setting-information-form').find('button'));
       }
     });
   });
   var pac_input = document.getElementById('address');
     (function pacSelectFirst(input) {
       // store the original event binding function
       var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
       function addEventListenerWrapper(type, listener) {
         // Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
         // and then trigger the original listener.
         if(type == "keydown") {
           var orig_listener = listener;
           listener = function (event) {
             var suggestion_selected = $(".pac-item-selected").length > 0;
             if(event.which == 13 && !suggestion_selected) {
               var simulated_downarrow = $.Event("keydown", {
                 keyCode: 40,
                 which: 40
               });
               orig_listener.apply(input, [simulated_downarrow]);
             }
             orig_listener.apply(input, [event]);
           };
         }
         // add the modified listener
         _addEventListener.apply(input, [type, listener]);
       }
       if(input.addEventListener)
         input.addEventListener = addEventListenerWrapper;
       else if(input.attachEvent)
         input.attachEvent = addEventListenerWrapper;
     })(pac_input);
   
     $(function () {
        var autocomplete = new google.maps.places.Autocomplete(pac_input);
     });
</script>