<li class="feeds-item" data-id="<?php echo $_user['id']; ?>">
    <div class="data-container <?php if($_small){ ?>small<?php } ?>">
        <a href="<?php echo $wo['config']['site_url']; ?>/<?php echo $_user['user_name']; ?>">
            <img class="data-avatar" src="<?php echo $_user['user_picture']; ?>" alt="<?php echo $_user['user_fullname']; ?>">
        </a>
        <div class="data-content">
            <div class="pull-right flip">
			  <?php if($wo['user']['user_id'] != $_user['user_id']){ ?>
               
			   <?php if($wo['config']['user_lastseen'] == 1 && $_user['showlastseen'] != 0) { ?>
   				<div class="user-lastseen">
   		   		<?php echo Wo_UserStatus($_user['user_id'],$_user['lastseen']); ?>
   				</div>
   		
				<?php if (!isset($_user['no_btn'])) { ?>
   				<div class="user-follow-button">
   		   		<?php echo Wo_GetFollowButton($_user['user_id']);?>
   				</div>
   				<?php } ?>
                <?php } ?>

			   
			 <?php } ?>
            </div>
            <div>
                <span class="name js_user-popover" data-uid="<?php echo $_user['user_id']; ?>">
                    <a href="<?php echo $wo['config']['site_url']; ?>/<?php echo $_user['user_name']; ?>"><?php echo $_user['user_fullname']; ?></a>
                </span>
            </div>
			<div><?php echo $wo['lang']['plugin_point_points']; ?>: <?php echo $_user['totalearned']; ?></div>
			<div><?php echo $wo['lang']['plugin_point_rank']; ?>: <?php echo $_user['user_rank']; ?></div>
            
        </div>
    </div>
</li>