<div class="col-sm-14 panel" id="pre-website-ads-container">
    <div class="panel-body">
        <form  action="" method="post">
            <input type="text" class="form-control input_get_website" placeholder="<?php echo $wo['lang']['plugin_ads_enter_link']; ?>"/>
            <button class="btn btn-success"><?php echo $wo['lang']['plugin_ads_continue']; ?></button>
            <div class="alert alert-danger"><?php echo $wo['lang']['plugin_ads_invalid_link']; ?></div>
        </form>
    </div>
</div>

<div class="row website-ads-add-container"><?php //include "ajax_ads_get_website.phtml"; ?></div>