<li class="feeds-item poke poke_<?php echo $friend['user_id']; ?>" data-id="<?php echo $friend['user_id']; ?>">
   <div class="data-container">
        <a href="<?php echo $wo['config']['site_url']; ?>/<?php echo $friend['username']; ?>">
			<img class="data-avatar" src="<?php echo $friend['user_picture']; ?>" alt="<?php echo $friend['username']; ?>">
		</a>
        <div class="data-content">
			
			<div class="pull-right flip delete_poke"><button type="button" class="close"><span>×</span></button></div>
				
			<div class="poke_sending pull-right flip x-hidden">¡<?php echo $wo['lang']['plugin_poke_gave_a_poke']; ?> <a href="<?php echo $wo['config']['site_url'];?>/<?php echo $friend['username']; ?>"><?php echo $friend['username']; ?></a>!</div>
			
            <div class="pull-right flip">
				<button type="button" class="btn btn-primary btn_poke" data-id="<?php echo $friend['user_id']; ?>">
				<img src="<?php echo $wo['config']['site_url'];?>/assets/plugins/img/toqueb.png">
				<span class="ml5"><?php echo $wo['lang']['plugin_poke_give_a_poke']; ?></span>
				</button>
			</div>
			
            <div>
                <span class="name js_user-popover"  data-uid="<?php echo $friend['user_id']; ?>" data-type="user">
                    <a href="<?php echo $wo['config']['site_url'];?>/<?php echo $friend['username']; ?>"><?php echo $friend['user_fullname']; ?></a>
                </span>
            </div>
			
        </div>
    </div>
</li>