<?php 
    $page_id = ( isset($_POST['page_id']) ? $_POST['page_id'] : ( isset($_GET['page_id']) ? $_GET['page_id'] : 0 ) );
	global $sqlConnect;

	// get page info
	$page_id = Wo_Secure($page_id);
	$user_id = Wo_Secure($wo['user']['user_id']);

    $get_page = $sqlConnect->query("SELECT * FROM Wo_Pages WHERE page_id = '{$page_id}' AND user_id= '{$user_id}' ORDER BY page_id DESC LIMIT 1");

    if($get_page->num_rows == 0) { 
       $data = array('result' => 1, 'message' => 'no exist page');
	   /* return */
       return_json($data);
    }
	 
    $info_page = $get_page->fetch_assoc();

	$info_page['photo'] =  $wo['config']['site_url'].'/'.$info_page['avatar'];
	$info_page['page_description'] = (strlen($info_page['page_description']) > 99) ?  substr_replace($info_page['page_description'],"",99) : '';
	$info_page['count_desc'] = (99) - strlen($info_page['page_description']);  
	
    $where = " type='clicks' ";   
	// get plans
	$plans = Ads::get_plans("", FALSE, FALSE, "id DESC", $where);	
?>
    <form class="ads-add-form" action="" method="post">
        <input type="hidden" name="type" value="page"/>
        <input type="hidden" name="id" id="ads-id" value=""/>
        <input type="hidden" name="page_id" value="<?php echo $info_page['page_id']; ?>"/>
        <div class="col-sm-7">
            <div class="panel panel-default">
                <div class="panel-heading"><?php echo $wo['lang']['plugin_ads_ads_info']; ?></div>
                <div class="panel-body panel-default">
                    <div class="form-group">
                        <label for="exampleInputEmail1"><?php echo $wo['lang']['plugin_ads_campaign_name']; ?></label>
                        <input name="campaign_name" type="text" value="<?php echo $info_page['page_name']; ?> - Page likes" class="form-control" id="exampleInputEmail1" placeholder="<?php echo $wo['lang']['plugin_ads_campaign_name']; ?>">
                    </div>

                    <div class="form-group">
                        <label><?php echo $wo['lang']['plugin_ads_ads_text']; ?></label><div class="pull-right flip js_count_d"><?php echo $info_page['count_desc']; ?></div>
                        <textarea maxlength="99" name="description" class="form-control error_d"><?php echo $info_page['page_description']; ?></textarea>
                    </div>

                    <div class="panel-heading"><?php echo $wo['lang']['plugin_ads_select_image']; ?></div>

                    <div class="ads-image-container">

                        <input class="ads-image-hidden-input" name="imagen" type="hidden" value="<?php echo $info_page['photo']; ?>" >
                        <img class="ads-image" src="<?php echo $info_page['photo']; ?>"/>

                        <div style="display: none" class="alert alert-danger" id="ads-image-error"><?php echo $wo['lang']['plugin_ads_error']; ?></div>
                        <div   class=" fileupload fileupload-exists" data-provides="fileupload">

                            <a   class="btn-file btn btn-sm btn-danger">
                                <span class="fileupload-new"><?php echo $wo['lang']['plugin_ads_change_image']; ?></span>
                                <span class="fileupload-exists"><?php echo $wo['lang']['plugin_ads_change_image']; ?></span>

                                <input id="ads-image-input" multiple  class="" type="file" name="image">
                            </a>
                            <img class="ad-image-indicator" src="<?php echo $wo['config']['site_url']; ?>/assets/plugins/img/load.gif" width="20" height="20"/>
                        </div>
                    </div>

                    <div class="panel-heading"><?php echo $wo['lang']['plugin_ads_how_to_spend']; ?></div>
                    <div class="form-group">
                        <label><?php echo $wo['lang']['plugin_ads_optimize_for']; ?></label>
                        <select style="width: 60%" class="form-control ads-plan-type" name="plan_type">
                            <option value="clicks"><?php echo $wo['lang']['plugin_ads_clicks']; ?></option>
                            <option value="impression"><?php echo $wo['lang']['plugin_ads_impression']; ?></option>
							<option value="period">Period</option>
                        </select>

                    </div>
                    <div class="form-group">
                        <label><?php echo $wo['lang']['plugin_ads_how_much_to_spend']; ?></label>
                        <select style="width: 60%" class="form-control ads-plans" name="plan_id">
							<?php foreach($plans as $plan){ ?>
                            <option value="<?php echo $plan['id']; ?>"><?php echo $plan['name']; ?> (<?php echo $plan['price'].' '.$plan['money_type'];; ?>)</option>
                            <?php } ?>
                        </select>

                    </div>

                </div>
            </div>
        </div>

        <div class="col-sm-5">
		  <div class="panel">
            <ul class="panel-body user-action-buttons">
                <li><a class="preview-ad" data-id="<?php echo $ad['id']; ?>" href=""><i class="icon ion-android-search"></i> <span><?php echo $wo['lang']['plugin_ads_preview_ad']; ?></span></a> </li>
            </ul>
		  </div>
            <div class="panel panel-default">
                <div class="panel-heading"><?php echo $wo['lang']['plugin_ads_who_do_ad_reach']; ?></div>
                <div class="panel-body">
             
			 <?php /* Disable in this version */ include "ads_tab_countries.phtml"; ?>

                    <label><?php echo $wo['lang']['plugin_ads_gender']; ?></label>
                    <select name="gender" class="form-control">
                        <option value="all"><?php echo $wo['lang']['plugin_ads_all']; ?></option>
                        <option value="M"><?php echo $wo['lang']['plugin_ads_male']; ?></option>
                        <option value="F"><?php echo $wo['lang']['plugin_ads_female']; ?></option>
                    </select>
                </div>

                <div class="ads-add-footer">

                    <button href="" class="ad-save-button btn btn-sm btn-primary"><?php echo $wo['lang']['plugin_ads_save_ad']; ?></button>
                    <a href="" class="btn ad-save-and-activate btn-sm btn-success"><?php echo $wo['lang']['plugin_ads_save_and_activate']; ?></a>
                </div>
            </div>
			<div class="panel panel-default col-sm-12">
                    <a data-warning="<?php echo $wo['lang']['plugin_ads_delete_ad_warning']; ?>"  style="margin:30px 10px" href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=ads" class="btn btn-danger delete-ad-button"><?php echo $wo['lang']['plugin_ads_delete_cancel_ad']; ?></a>
            </div>
        </div>
    </form>