<style>
    .col-sm-6{
        padding:0px;
    }
    cv-tag .carousel {
        width: 97%;
        margin-left: 1%;
        float: left;
    }

    cv-tag .carousel-control.left, .carousel-control.right {
        background-image:none;
    }

    .img-responsive{
        width:100%;
        height:auto;
    }

    @media (min-width: 992px ) {
        cv-tag .carousel-inner .active.left {
            left: -25%;
        }
        cv-tag .carousel-inner .next {
            left:  25%;
        }
        cv-tag .carousel-inner .prev {
            left: -25%;
        }
    }

    @media (min-width: 768px) and (max-width: 991px ) {
        cv-tag .carousel-inner .active.left {
            left: -33.3%;
        }
        cv-tag .carousel-inner .next {
            left:  33.3%;
        }
        cv-tag .carousel-inner .prev {
            left: -33.3%;
        }
        cv-tag .carousel-inner .active > div:first-child {
            display:block;
        }
        cv-tag .carousel-inner .active > div:first-child + div {
            display:block;
        }
        cv-tag .carousel-inner .active > div:last-child {
            display:none;
        }
    }

    @media (max-width: 767px) {
        cv-tag .carousel-inner .active.left {
            left: -100%;
        }
        cv-tag .carousel-inner .next {
            left:  100%;
        }
        cv-tag .carousel-inner .prev {
            left: -100%;
        }
        cv-tag .carousel-inner .active > div {
            display:none;
        }
        cv-tag .carousel-inner .active > div:first-child {
            display:block;
        }
    }
    .cv-tag .carousel-control.right{
        top: 40%;
        width: 40px;
        right: -5px;
    }
    .cv-tag .carousel-control.left{
        top: 40%;
        width: 40px;
        left: -5px;
        background: none;
    }
    .cv-cc{
        width: 100%;
        float: right;
    }
    .cv-cc .cv-left{
        float: left;
        width: 100%;
    }
    .cv-cc .cv-left .nav-top{
        float: left;
        width: 100%;
    }
    .cv-cc .cv-left .nav-top .cv-menu{
        float: left;
        border: 1px solid #17aa9d;
        border-radius: 20px;
    }
    .cv-cc .cv-left .nav-top .cv-menu a{
        padding: 6px 20px;
        float: left;
        color: #17aa9d;
        font-size:13px;
        text-transform: uppercase;
    }
    .cv-cc .cv-left .nav-top .com-article{
        background: url(<?php echo $wo['config']['theme_url'];?>/img/icon-cobo.png) 101% / 33px no-repeat !important;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        float: right;
        width: 180px;
        height: 33px;
        padding: 0px 5px;
        margin-bottom: 14px;
        border: 1px solid #17aa9d;
        outline: none;
    }
    .cv-cc .cv-left .h4-click{
        float: left;
        width: 100%;
        text-decoration: underline;
        font-size: 15px;
    }
    .cv-cc .cv-left .cv-country{
        float: left;
        width: 100%;
        margin-top: 10px;
    }
    .cv-cc .cv-left .cv-country .a-flag{
        width: 20%;
        float: left;
    }
    .cv-cc .cv-left .cv-country .a-flag img{
        width: 30px;
    }
    .cv-cc .cv-left .cv-country .sp-more{
        margin-top: 10px;
        float: right;
    }
    .cv-cc .cv-left .cv-country .sp-more .p-more{
        float: left;
        margin-right: 5px;
    }
    .cv-cc .cv-left .cv-tag{
        float: left;
        width: 100%;
        margin-bottom: 20px;
    }
    .cv-cc .cv-left .cv-tag .item-mxh{
        width: 90%;
        overflow: hidden;
        margin-left: 6%;
        margin-top: 20px;
    }
    .cv-cc .cv-left .cv-tag .item-mxh .a-tag{
        background: #17aa9d;
        margin-right: 2.5%;
        padding: 6px 0px;
        float: left;
        font-size: 13px;
        border-radius: 50px;
        color: #fff;
        text-align: center;
        width: 17%;
    }
    .cv-cc .cv-left .cv-tag .item-mxh .a-tag:hover, .cv-cc .cv-left .nav-top .cv-menu a:hover{
        text-decoration: none;
    }
    .cv-social{
        position: fixed;
        display: none;
        top: 170px;
        text-align: center;
        margin-left: -75px;
    }
    .cv-social .p-like-page{
        float: left;
        font-size: 15px;
    }
    .cv-social .a-social{
        display: block;
        margin-bottom: 7px;
    }
    .cv-social .a-social img{
        width: 45px;
    }
    .cv-right{
        float: left;
        width: 28%;
        margin-left: 2%;
    }
    .cv-right .area-ads{
        background: #17aa9d;
        float: left;
        height: 200px;
        width: 100%;
    }
    .cv-cc .cv-left .cv-item-home{
        float: left;
        width: 100%;
        margin-top: 20px;
    }
    .cv-cc .cv-left .cv-item-home .item-home{
        float: left;
        width: 100%;
        border: 1px solid #ccc;
        background: #fff;
        padding: 15px;
        margin-bottom: 20px;
    }
    .cv-cc .cv-left .cv-item-home .item-home .h3-tit{
        float: left;
        width: 100%;
        text-transform: capitalize;
        padding: 0px;
        margin: 7px 0px;
    }
    .cv-cc .cv-left .cv-item-home .item-home .sp-date{
        float: left;
        width: 100%;
        font-size: 13px;
        color: #777;
    }
    .cv-cc .cv-left .cv-item-home .item-home .img-ac{
        margin-top: 20px;
        float: left;
        width: 100%;
    }
    .cv-cc .cv-left .cv-item-home .item-home .cv-report{
        float: left;
        width: 100%;
        text-align: right;
        margin-top: 8px;
    }
    .cv-cc .cv-left .cv-item-home .item-home .cv-report .sp-report{
        font-size: 13px;
    }
    .cv-cc .cv-left .cv-item-home .item-home .cv-bot{
        float: left;
        width: 100%;
    }
    .cv-cc .cv-left .cv-item-home .item-home .cv-bot .img-left{
        float: left;
    }
    .cv-cc .cv-left .cv-item-home .item-home .cv-bot .img-right{
        float: right;
        margin-top: 35px;
    }
    .cv-right .cv-vid-right{
        float: left;
        width: 265px;
        position: fixed;
    }
    .cv-right .cv-vid-right .h4-hot-video{
        float: left;
        width: 100%;
        text-align: left;
        text-transform: uppercase;
        font-size: 14px;
        padding: 6px 5px;
        border-bottom: 1px solid #f1f1f1;
    }
    .list-group-item:first-child{
        text-transform: uppercase;
    }
    .cv-right .cv-vid-right .item-hot-video{
        float: left;
        width: 100%;
        border: 1px solid #ccc;
        background: #fff;
        padding: 5px 15px;
        margin-bottom: 20px;
    }
    .cv-right .cv-vid-right .item-hot-video .h3-tit{
        float: left;
        width: 100%;
        text-transform: capitalize;
        padding: 0px;
        margin: 7px 0px;
        line-height: 18px;
        font-size: 15px;
    }
    .cv-right .cv-vid-right .item-hot-video .sp-date{
        float: left;
        width: 100%;
        font-size: 13px;
        color: #777;
    }
    .cv-right .cv-vid-right .item-hot-video .img-ac{
        margin-top: 10px;
        float: left;
        width: 100%;
    }
    .cv-right .cv-vid-right .item-hot-video .cv-bot{
        float: left;
        width: 100%;
    }
    .cv-right .cv-vid-right .item-hot-video .cv-bot .img-left{
        float: left;
        width: 65%;
        margin: 5px 0px;
    }
    .cv-menu a.active{
        background: #17aa9d;
        color: #fff !important;
        border-radius: 20px;
        font-weight: bold;
        text-decoration: none;
    }
    .cv-mem{
        float: left;
        width: 100%;
        margin-bottom: 20px;
        box-shadow: 0 1px 0 0 #e3e4e8, 0 0 0 1px #f1f1f1;
    }

    #sidebar-sticky{
        float: left;
        width: 100%;
    }
    @media(max-width:990px) {
        .cv-cc .cv-left {
            width: 100%;
        }
        .cv-right {
            display: none;
        }
        .cv-social {
            display: none;
        }
    }
    @media(max-width:600px) {
        .cv-cc .cv-left .nav-top .com-article{
            width: 100%;
            margin-top: 10px;
            margin-bottom: 0px;
        }
        .cv-cc .cv-left .cv-country .a-flag span{
            width: 100%;
            float: left;
        }
        .cv-cc .cv-left .cv-country .a-flag {
            width: 21%;
        }
        .cv-cc .cv-left .cv-country {
            text-align: center;
        }
        .cv-cc .cv-left .cv-tag .item-mxh .a-tag {
            margin-right: 1.5%;
            font-size: 10px;
            border-radius: 8px;
            width: 18%;
        }
        .cv-cc .cv-left .nav-top .cv-menu {
            width: 100%;
        }
        .cv-cc .cv-left .nav-top .cv-menu a {
            text-align: center;
            width: 25%;
        }
        .cv-cc .cv-left .cv-country .sp-more{
            margin-top: 30px;
        }
        .cv-cc .cv-left .cv-country .sp-more .p-more{
            display: none;
        }
    }
</style>
<?php
$hashtag = '';
if (isset($_GET['link1']) && $_GET['link1'] == 'hashtag' && !empty($_GET['hash'])) {
  $hashtag = '#' . $_GET['hash'];
}
?>
<form action="#" method="post" class="post publisher-box publisher_box">

	<?php if(!empty($wo['system']['combo_enable_dragdrop'])  && $wo['system']['combo_enable_dragdrop'] == 1 && in_array('Combo', $wo['plugin_list']['plugin_actived'] )){ ?>
		<div class="_1zja"><div class="_1zjb"><span class="_1zjd"><?php echo $wo['lang']['plugin_combo_drag_link_photo']; ?></span><span class="_4_9w"><?php echo $wo['lang']['plugin_combo_place_you_link']; ?></span><span class="_4_9x"><?php echo $wo['lang']['plugin_combo_place_the_photo']; ?></span></div></div>
	<?php } ?>

   <div class="panel panel-white post panel-shadow">
      <div id="post-textarea">
         <i class="fa fa-spinner fa-spin" id="loading_indicator"></i>
		 
		 <?php /* publisher tabs */ ?>
    <ul class="publisher-tabs clearfix">
        <li>
            <span class="active js_publisher_tab" data-tab="post">
                <i class="fa fa-pencil fa-fw"></i> <?php echo $wo['lang']['plugin_write_post']; ?>
            </span>
        </li>

            <li class="hidden-xs">
                <span class="js_publisher_tab" onclick="Wo_OpenAlbum();" data-tab="album">
                    <i class="fa fa-picture-o fa-fw"></i> <?php echo $wo['lang']['plugin_create_album']; ?>
                </span>
            </li>

<?php /* plugin wall up */ echo Wo_LoadPage('plugins/plugin_wall_menu_up_1'); /* plugin wall up */ ?>

        <li class="dropdown">
            <span class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-bars fa-fw"></i> <?php echo $wo['lang']['plugin_more']; ?>
            </span>
            <ul class="dropdown-menu">
                    <li class="visible-xs-block">
                        <span class="publisher-tools-attach js_publisher_tab" onclick="Wo_OpenAlbum();" data-tab="albums">
                            <i class="fa fa-picture-o fa-fw"></i> <?php echo $wo['lang']['plugin_create_album']; ?>
                        </span>
                    </li>
<?php /* plugin wall up */ echo Wo_LoadPage('plugins/plugin_wall_menu_up_2'); /* plugin wall up */ ?>
                 
                <?php if ($wo['config']['video_upload'] == 1) { ?>
                    <li>
                        <span class="publisher-tools-attach js_publisher_tab btn-file" data-tab="video">
                            <i class="fa fa-video-camera fa-fw js_x-uploader" data-handle="publisher" data-type="video"></i> <?php echo $wo['lang']['plugin_add_video']; ?>
							<input type="file" id="publisher-video" name="postVideo" accept="video/*">
                        </span>
                    </li>
                <?php } ?>
                <?php if ($wo['config']['audio_upload'] == 1) { ?>
                    <li>
                        <span class="publisher-tools-attach js_publisher_tab btn-file" data-tab="audio">
						<i class="fa fa-music fa-fw js_x-uploader" data-handle="publisher" data-type="audio"></i> <?php echo $wo['lang']['plugin_add_audio']; ?>
						<input type="file" id="publisher-music" name="postMusic" accept="audio/*">
                        </span>
                    </li>
                <?php } ?>
                <?php if($wo['config']['fileSharing'] == 1) { ?>
                    <li>
                        <span class="publisher-tools-attach js_publisher_tab btn-file" data-tab="audio">
                            <i class="fa fa-file-text-o fa-fw js_x-uploader" data-handle="publisher" data-type="file"></i> <?php echo $wo['lang']['plugin_add_file']; ?>
							<input type="file" id="publisher-file" name="postFile">
                        </span>
                    </li>
                <?php } ?>
				<?php if (($wo['page'] == 'home' || $wo['page'] == 'timeline') && $wo['config']['classified'] == 1) { ?>
                    <a href="<?php echo Wo_SeoLink('index.php?link1=new-product');?>"><li>
                        <span class="publisher-tools-attach btn-file" data-tab="classified">
                            <i class="fa fa-shopping-cart fa-fw js_x-uploader"></i> <?php echo $wo['lang']['plugin_add_product']; ?>
                        </span>
                    </li></a>
                <?php } ?>		 
            </ul>
        </li>
    </ul>
    <?php /* publisher tabs */ ?>	
		 <img class="post-avatar" src="<?php echo (empty($wo['page_profile']['avatar'])) ? $wo['user']['avatar'] : $wo['page_profile']['avatar'];?>">
		 <textarea onkeyup="textAreaAdjust(this, 70)" onclick="Wo_ShowPosInfo();" name="postText" class="form-control postText" cols="10" rows="3" placeholder="<?php echo $wo['lang']['publisher_box_placeholder']; ?>" dir="auto"><?php echo $hashtag;?></textarea> 
      </div>
	  
	  <?php /* plugin attachments */ ?>	
		  <div class="publisher-attachments attachments clearfix x-hidden">
			<ul></ul>
		  </div>
	  <?php /* plugin attachments */ ?>	
	  
      <?php if ($wo['config']['video_upload'] == 1) { ?>
      <div class="publisher-hidden-option" id="video-form">
         <div class="inner-addon <?php echo Wo_RightToLeft('left-addon');?>">
            <i class="glyphicon fa fa-video-camera"></i>
            <input name="videocount" type="text" class="form-control" readonly>
         </div>
      </div>
      <?php } ?>
      <?php if ($wo['config']['audio_upload'] == 1) { ?>
      <div class="publisher-hidden-option" id="music-form">
         <div class="inner-addon <?php echo Wo_RightToLeft('left-addon');?>">
            <i class="glyphicon fa fa-music"></i>
           <input name="musiccount" type="text" class="form-control" readonly>
         </div>
      </div>
      <?php } ?>
      <div id="poll-form">
        <div class="publisher-hidden-option answers">
           <input name="answer[]" type="text" class="form-control" placeholder="<?php echo $wo['lang']['answer'] ?> 1">
           <input name="answer[]" type="text" class="form-control" placeholder="<?php echo $wo['lang']['answer'] ?> 2">
        </div>
        <div class="create-album <?php echo Wo_RightToLeft('pull-right');?>" onclick="Wo_AddAnswer();" id="add_answer">
           <div class="create-text">
            <i class="fa fa-plus"></i> <?php echo $wo['lang']['add_answer'] ?>
           </div>
         </div>
      </div>
      <div id="album-form">
        <div class="publisher-hidden-option">
           <input name="album_name" type="text" class="form-control" placeholder="<?php echo $wo['lang']['album_name'];?>">
        </div>
       </div>
      <div class="publisher-hidden-option" id="photo-form">
         <div class="inner-addon <?php echo Wo_RightToLeft('left-addon');?>">
            <i class="glyphicon fa fa-file-image-o"></i>
            <input name="phtoscount" type="text" class="form-control" readonly>
         </div>
         <div class="create-album <?php echo Wo_RightToLeft('pull-right');?>" onclick="Wo_OpenAlbum();">
           <div class="create-text">
             <?php echo $wo['lang']['create_album'];?>
           </div>
         </div>
         <div class="clear"></div>  
      </div>
      <div class="publisher-hidden-option" id="file-form">
         <div class="inner-addon <?php echo Wo_RightToLeft('left-addon');?>">
            <i class="glyphicon fa fa-file-text-o"></i>
            <input name="filename" type="text" class="form-control" readonly>
         </div>
      </div>
      <div class="publisher-hidden-option" id="map-form">
         <div class="inner-addon <?php echo Wo_RightToLeft('left-addon');?>">
            <i class="glyphicon fa fa-map-marker"></i>
            <input name="postMap" id="searchTextField" type="text" class="form-control" placeholder="<?php echo $wo['lang']['maps_placeholder']?>">
         </div>
      </div>
	  <?php /* plugin wall tabs */ echo Wo_LoadPage('plugins/plugin_wall_menu_tabs'); /* plugin wall tabs */ ?>
      <div id="emo-form">
        <div class="publisher-hidden-option">
            <div class="feelings-type-to <?php echo Wo_RightToLeft('pull-left');?> pointer" onclick="Wo_RestFeelings();"></div>
            <span class="feelings-value"></span>
            <input name="feeling" id="feelings-text" type="text" class="form-control" placeholder="<?php echo $wo["lang"]["feel_d"]?>" onclick="Wo_ShowFeelings();" autocomplete="no">
            <input name="feeling_type" type="hidden" id="feeling-type" value="">
            <div class="clear"></div>
        </div>
        <div class="feeling-type feeling-types">
          <ul>
            <li class="pointer" onclick='Wo_ShowFeelingType("feelings", "<?php echo $wo['lang']['feeling'];?>", "<?php echo $wo['lang']['feeling_q'];?>", "smile-o");'>
              <i class="fa fa-fw fa-smile-o fa-wh"></i> <?php echo $wo['lang']['feeling'];?>
            </li>
            <li class="pointer" onclick='Wo_ShowFeelingType("traveling", "<?php echo $wo['lang']['traveling'];?>" , "<?php echo $wo['lang']['traveling_q'];?>", "plane");'>
              <i class="fa fa-fw fa-plane"></i> <?php echo $wo['lang']['traveling'];?>
            </li>
            <li class="pointer" onclick='Wo_ShowFeelingType("watching", "<?php echo $wo['lang']['watching'];?>", "<?php echo $wo['lang']['watching_q'];?>", "eye");'>
              <i class="fa fa-fw fa-eye"></i> <?php echo $wo['lang']['watching'];?>
            </li>
            <li class="pointer" onclick='Wo_ShowFeelingType("playing", "<?php echo $wo['lang']['playing'];?>", "<?php echo $wo['lang']['playing_q'];?>", "gamepad");'>
              <i class="fa fa-fw fa-gamepad"></i> <?php echo $wo['lang']['playing'];?>
            </li>
            <li class="pointer" onclick='Wo_ShowFeelingType("listening", "<?php echo addslashes($wo['lang']['listening']);?>", "<?php echo addslashes($wo['lang']['listening_q']);?>", "headphones");'>
              <i class="fa fa-fw fa-headphones"></i> <?php echo $wo['lang']['listening'];?>
            </li>
          </ul>
        </div>
        <div class="feeling-type feelings">
          <ul>
            <?php 
            foreach ($wo['feelingIcons'] as $icon_name => $icon_code) {
            ?>
            <li class="pointer" onclick="Wo_AddFeeling('<?php echo $icon_name;?>', '<?php echo $wo['lang'][$icon_name]; ?>', '<?php echo $icon_code;?>');"><i class="twa-lg twa twa-<?php echo $icon_code; ?>"></i> <?php echo $wo['lang'][$icon_name]; ?></li>
            <?php
            }
            ?>
          </ul>
        </div>
         <?php  
        foreach ($wo['emo'] as $code => $name) {
            $code   = $code;
            echo  '<span onclick="Wo_AddEmo(\'' . $code . '\',\'#post-textarea textarea\');"><i class="pointer twa-lg twa twa-' . $name . '"></i></span>';
        } 
        ?>
      </div>
      <div id="results"></div>
      <div class="publisher-hidden-option">
         <div id="progress">
            <span id="percent">0%</span>
            <div class="progress">
             <div id="bar" class="progress-bar progress-bar-striped active"></div> 
            </div>
            <div class="clear"></div>
         </div>
      </div>
      <div class="publisher-box-footer">
         <div class="row col-lg-2 <?php echo Wo_RightToLeft('pull-right');?>">
            <button type="submit" id="publisher-button"class="form-control btn btn-main">
            <i class="fa fa-edit progress-icon " data-icon="edit"></i> <span id="postbutton"><?php echo $wo['lang']['post_label']; ?></span></button>
         </div>
        <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file">
                  <i class="fa fa-camera" ></i><input type="file" id="publisher-photos" accept="image/x-png, image/gif, image/jpeg" name="postPhotos[]" multiple="multiple">
                  </span>
               </div>
            </div>
         </div>
         <?php if ($wo['config']['video_upload'] == 1) { ?>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file">
                  <i class="fa fa-video-camera"></i><input type="file" id="publisher-video" name="postVideo" accept="video/*">
                  </span>
               </div>
            </div>
         </div>
         <?php } ?>
         
         <div class="row <?php echo Wo_RightToLeft('pull-left');?> emo-form" >
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file">
                  <i class="fa fa-smile-o "></i>
                  </span>
               </div>
            </div>
         </div>
		 
		 <?php include "plugin_wall_menu_down.phtml"; ?>
		 
          <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <div class="dropdown">
  <button class="btn btn-default btn-file dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
  <ul class="dropdown-menu">
    <li>
      <?php if($wo['config']['fileSharing'] == 1) { ?>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file">
                  <i class="fa fa-file-text-o"></i><input type="file" id="publisher-file" name="postFile">
                  </span>
               </div>
            </div>
         </div>
         <?php } ?>
         <?php if (($wo['page'] == 'home' || $wo['page'] == 'timeline') && $wo['config']['classified'] == 1) { ?>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <a href="<?php echo Wo_SeoLink('index.php?link1=new-product');?>" class="btn btn-default btn-file">
                  <i class="fa fa-shopping-cart"></i>
                  </a>
               </div>
            </div>
         </div>
         <?php } ?>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                   <span class="btn btn-default btn-file poll-form">
                     <i class="fa fa-pie-chart"></i>
                  </span>
               </div>
            </div>
         </div>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file map-form">
                  <i class="fa fa-map-marker"></i>
                  </span>
               </div>
            </div>
         </div>
         <?php if ($wo['config']['audio_upload'] == 1) { ?>
         <div class="row <?php echo Wo_RightToLeft('pull-left');?>">
            <div class="poster-left-buttons">
               <div class="input-group">
                  <span class="btn btn-default btn-file">
                  <i class="fa fa-music"></i><input type="file" id="publisher-music" name="postMusic" accept="audio/*">
                  </span>
               </div>
            </div>
         </div>
         <?php } ?>
    </li>
  </ul>
</div>
               </div>
            </div>
         </div>
         
         
         <div class="input-group">
            <div class="<?php echo Wo_RightToLeft('pull-right');?> charsLeft-post"><span id="charsLeft"></span></div>
         </div>
         <div id="status"></div>
         <?php if (!isset($wo['input']['recipient']) && $wo['page'] != 'group') { ?>
         <div class="row <?php echo Wo_RightToLeft('pull-right');?>">
            <div class="poster-left-buttons">
               <div class="publisher-hidden-option inputsm">
                  <select name="postPrivacy" class="form-control inputsm">
                     <?php if (empty($_GET['p'])) {?>
                        <option value="3"><?php echo $wo['lang']['only_me'];?></option>
                        <option value="0"><?php echo $wo['lang']['everyone'];?></option>
                        <?php if ($wo['config']['connectivitySystem'] == 0) { ?>
                        <option value="1"><?php echo $wo['lang']['people_i_follow'];?></option>
                        <option value="2"><?php echo $wo['lang']['people_follow_me'];?></option>
                        <?php } else {?>
                        <option value="1" selected><?php echo $wo['lang']['my_friends'];?></option>
                        <?php }?>
                     <?php } else { ?>
                        <option value="0"><?php echo $wo['lang']['everyone'];?></option>
                        <option value="2"><?php echo $wo['lang']['liked_my_page'];?></option>
                     <?php } ?>
                  </select>
               </div>
            </div>
         </div>
         <?php } ?>
         <div class="clear"></div>
      </div>
   </div>
   <?php if (isset($wo['input']['recipient'])) { ?>
   <input type="hidden" name="recipient_id" value="<?php echo $wo['user_profile']['user_id']; ?>">
   <?php } ?>
   <?php if ($wo['page'] == 'page') {?>
   <input type="hidden" name="page_id" value="<?php echo $wo['page_profile']['page_id']; ?>">
   <?php } else if ($wo['page'] == 'group') {?>
   <input type="hidden" name="group_id" value="<?php echo $wo['group_profile']['id']; ?>">
   <?php } ?>
   <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
</form>
<?php if ($wo['page'] == 'home') { ?>
<div class="filter-margin">
    <div class="btn-group filter-container">
        <button type="button" onclick="Wo_FilterPostBy('all');" class="btn filter btn-main type-all">
            <i class="fa fa-bars progress-icon" data-icon="bars"></i>
            <span class="filter-text"> <?php echo $wo['lang']['all']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('text');" class="btn filter btn-main type-text">
            <i class="fa fa-pencil progress-icon" data-icon="pencil"></i>
            <span class="filter-text"> <?php echo $wo['lang']['text']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('photos');" class="btn filter btn-main type-photos">
            <i class="fa fa-file-image-o progress-icon" data-icon="file-image-o"></i>
            <span class="filter-text"> <?php echo $wo['lang']['photos']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('video');" class="btn filter btn-main type-video">
            <i class="fa fa-film progress-icon" data-icon="film"></i>
            <span class="filter-text"> <?php echo $wo['lang']['videos']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('music');" class="btn filter btn-main type-music">
            <i class="fa fa-music progress-icon" data-icon="music"></i>
            <span class="filter-text"> <?php echo $wo['lang']['sounds']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('files');" class="btn filter btn-main type-files">
            <i class="fa fa-file-text-o progress-icon" data-icon="file-text-o"></i>
            <span class="filter-text"> <?php echo $wo['lang']['files']; ?><span>
        </button>
        <button type="button" onclick="Wo_FilterPostBy('maps');" class="btn filter btn-main type-maps">
            <i class="fa fa-map-marker progress-icon" data-icon="map-marker"></i>
            <span class="filter-text"> <?php echo $wo['lang']['maps']; ?><span>
        </button>
    </div>
</div>
<?php } ?>
<div class="cv-cc">
    <div class="cv-left">
<div class="nav-top">
   <!-- <div class="cv-menu">
        <a href="#" class="active" onclick="Wo_FilterPostBy('all');">All</a>
        <a href="#" onclick="Wo_FilterPostBy('video');">videos</a>
        <a href="#" onclick="Wo_FilterPostBy('photos');">images</a>
        <a href="#" onclick="Wo_FilterPostBy('text');">news</a>
    </div>-->
    <!--<select class="com-article">
        <option>Chủ đề 01</option>
        <option>Chủ đề 02</option>
        <option>Chủ đề 03</option>
    </select>-->
</div>
<!--<h4 class="h4-click">Click chọn quốc gia yêu thích</h4>-->
<div class="cv-country">
    <a class="a-flag" href="#"><img src="<?php echo $wo['config']['theme_url'];?>/img/flag-us.png"/> <span>USA</span></a>
    <a class="a-flag" href="#"><img src="<?php echo $wo['config']['theme_url'];?>/img/flag-eng.png"/> <span>England</span></a>
    <a class="a-flag" href="#"><img src="<?php echo $wo['config']['theme_url'];?>/img/flag-vn.png"/> <span>Vietnam</span></a>
    <a class="a-flag" href="#"><img src="<?php echo $wo['config']['theme_url'];?>/img/flag-can.png"/> <span>Canada</span></a>
    <span class="sp-more"><p class="p-more">nhiều hơn </p> <img src="<?php echo $wo['config']['theme_url'];?>/img/icon-three.png"/></span>
</div>
<div class="cv-tag">
    <div class="carousel slide row" data-ride="carousel" data-type="multi" data-interval="400000" id="fruitscarousel1">
        <div class="carousel-inner">
            <?php
            $arrColor = ['#d19800','#8c9c01','#019c84','#01439c','#ae006a','#ffd209'];
            $hashtags = Wa_GetTrendingHashs('popular');
            if (count($hashtags) > 0) {
                foreach ($hashtags as $key => $wo['hashtag']) {
                    ?>
                    <div class="item <?php if($key == 0){echo "active";} ?> item-mxh">
                        <a class="a-tag" style="background: <?php echo $arrColor[$key] ?>" href="<?php echo $wo['hashtag']['url'];?>">#<?php echo $wo['hashtag']['tag'];?></a>
                    </div>
                    <?php
                }
            }
            ?>
        </div>
        <a class="left carousel-control" href="#fruitscarousel1" data-slide="prev"><img src="<?php echo $wo['config']['theme_url'];?>/img/icon-prev.png"/></a>
        <a class="right carousel-control" href="#fruitscarousel1" data-slide="next"><img src="<?php echo $wo['config']['theme_url'];?>/img/icon-next.png"/></a>
    </div>
</div>
    </div>
</div>
<div id="hidden_inputbox"></div>
<script type="text/javascript">
    jQuery('.carousel[data-type="multi"] .item').each(function () {
        var next = jQuery(this).next();
        if (!next.length) {
            next = jQuery(this).siblings(':first');
        }
        next.children(':first-child').clone().appendTo(jQuery(this));
        for (var i = 0; i < 3; i++) {
            next = next.next();
            if (!next.length) {
                next = jQuery(this).siblings(':first');
            }
            next.children(':first-child').clone().appendTo($(this));
        }
    });
$(function () {
  $('.postText').triggeredAutocomplete({
     hidden: '#hidden_inputbox',
     source: Wo_Ajax_Requests_File() + "?f=mention",
     trigger: "@" 
  });
  <?php if ($wo['config']['maxCharacters'] != 10000) { ?>
  $('.postText').limit("<?php echo $wo['config']['maxCharacters']?>", '#charsLeft');
  <?php } ?>
  $('.emo-form').click(function () {
    $('#emo-form').slideToggle(200);
    Wo_RestFeelings();
  });

  $('.map-form').click(function () {
    $('#map-form').slideToggle(200);
  });
  $('.poll-form').click(function () {
    $('#poll-form').slideToggle(200);
     $('.answers').find('input').each(function (index_id) {
       $(this).val('');
    });
  });
  $("#publisher-file").change(function () {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $("#file-form input").val(filename);
    $("#file-form").slideDown(200);
  });
  $("#publisher-photos").change(function () {
    var numFiles = this.files.length;
    $("#photo-form input").val(numFiles + ' photo(s) selected');
    $("#photo-form").slideDown(200);
  });

  $("#publisher-video").change(function () {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $("#video-form input").val(filename);
    $("#video-form").slideDown(200);
  });

  $("#publisher-music").change(function () {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $("#music-form input").val(filename);
    $("#music-form").slideDown(200);
  });

  var bar = $('#bar');
  var percent = $('#percent');
  var status = $('#status');
  var publisher_button = $('#publisher-button');

  $('form.post').ajaxForm({
    url: site_ajax+'?f=insert_new_post',
    beforeSend: function () {
      var percentVal = '0%';
      bar.width(percentVal);
      percent.html(percentVal);
      publisher_button.attr('disabled', true);
      publisher_button.css('color', '#333');
      Wo_progressIconLoader($('form.post').find('button'));
    },
    uploadProgress: function (event, position, total, percentComplete) {
      var percentVal = percentComplete + '%';
      bar.width(percentVal);
      $('#progress').slideDown(200);
      if(percentComplete > 50) {
        percent.addClass('white');
      }
      percent.html(percentVal);
    },
    success: function (data) {
      $('#progress').slideUp(200);
      publisher_button.attr('disabled', false);
      publisher_button.css('color', '#fff');
      percent.removeClass('white');
      $('.postText').css('height', 'auto');
      if(data.status == 200) {
        if(data.html.length > 0) {
          $('#posts, #posts_hashtag').find('.posts-container').remove();
        }
        $('#posts, #posts_hashtag').prepend(data.html);
        $('#video-form, #emo-form, #music-form, #map-form, #file-form, #photo-form, #album-form, .feeling-type, #poll-form').slideUp(200);
        Wo_RemoveFetchedUrl();
        $('form.post').clearForm();
        $('.feelings-value').html('');
        $('select').prop('selectedIndex', 1);
        <?php if ($wo['config']['maxCharacters'] != 10000) { ?>
        $('#charsLeft').text("<?php echo $wo['config']['maxCharacters']?>");
        <?php } ?>
		if(data.is_question != 0) { $('.js_publisher-question-remover').click(); }
		$('.tags').html('');
		$('.publisher_tag_friend').hide();
		$('.publisher_tag_friend').find('.who_are_you_with').val('');
		$('.js_tag_friend').removeClass('active');
      } else if (data.status == 400) {
        alert(data.errors);
      } 
      Wo_progressIconLoader($('form.post').find('button'));
    }
  });

  var pac_input = document.getElementById('searchTextField');
  (function pacSelectFirst(input) {
    // store the original event binding function
    var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
    function addEventListenerWrapper(type, listener) {
      // Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
      // and then trigger the original listener.
      if(type == "keydown") {
        var orig_listener = listener;
        listener = function (event) {
          var suggestion_selected = $(".pac-item-selected").length > 0;
          if(event.which == 13 && !suggestion_selected) {
            var simulated_downarrow = $.Event("keydown", {
              keyCode: 40,
              which: 40
            });
            orig_listener.apply(input, [simulated_downarrow]);
          }
          orig_listener.apply(input, [event]);
        };
      }
      // add the modified listener
      _addEventListener.apply(input, [type, listener]);
    }
    if(input.addEventListener)
      input.addEventListener = addEventListenerWrapper;
    else if(input.attachEvent)
      input.attachEvent = addEventListenerWrapper;
  })(pac_input);

  $(function () {
    var options = {
      language: 'en-GB',
      types: ['(cities)'],
      componentRestrictions: {}
    }
     var autocomplete = new google.maps.places.Autocomplete(pac_input, options);
     
  });
  var getUrl  = $('.form-control.postText'); //url to extract from text field

  $('.form-control.postText').on("paste keyup", function(e) { //user types url in text field    
    
    var match_url = /\b(https?):\/\/([\-A-Z0-9.]+)(\/[\-A-Z0-9+&@#\/%=~_|!:,.;]*)?(\?[A-Z0-9+&@#\/%=~_|!:,.;]*)?/i;
   
     if (($(".extracted_url").length > 0)){
       return false;
     }
    setTimeout(function () { 
   
    if (match_url.test(getUrl.val())) {
        
        $("#results").hide();
        $("#loading_indicator").show();
        
        var extracted_url = getUrl.val().match(match_url)[0];
        $.post(Wo_Ajax_Requests_File() + '?f=posts&s=fetch_url',{'url': extracted_url}, function(data){         
          extracted_images = data.images;
          total_images = parseInt(data.images.length-1);
          img_arr_pos = total_images;
          if(extracted_images != ''){
            inc_image = '<div class="extracted_thumb" id="extracted_thumb"><img src="'+data.images[img_arr_pos]+'"></div>';
            input_image = data.images[img_arr_pos];
          } else {
            inc_image = '';
            input_image = '';
          }
          
          var img_content = '';
          if (total_images > 1) {
            img_content = '<div class="thumb_select"><div class="thumb_sel"><span class="prev_thumb" id="thumb_next"><i class="fa fa-arrow-circle-right"></i></span><span class="next_thumb" id="thumb_prev"><i class="fa fa-arrow-circle-left"></i></span> </div><span class="small_text" id="total_imgs">'+img_arr_pos+' of '+total_images+'</span></div></div></div>';
          }
          var content = '<div class="extracted_url"><span class="remove-fetched-url" onclick="Wo_RemoveFetchedUrl();"><i class="fa fa-remove"></i></span>'+ inc_image +'<div class="extracted_content"><input class="form-control url-input" type="text" name="url_title" value="'+data.title+'" dir="auto"><br><textarea onkeyup="textAreaAdjust(this, 70)" class="form-control url-input-textarea url-input" name="url_content" placeholder="Description" dir="auto">' + data.content + '</textarea><input type="hidden" id="url_image" name="url_image" value="'+ input_image +'"><input type="hidden" id="url_link" name="url_link" value="'+data.url+'"><div class="clear"></div>' + img_content;
          $("#results").html(content); 
          $("#results").fadeIn(); 
          $("#loading_indicator").hide();
                },'json');
    }
    }, 100);
  });


  
  $("body").on("click","#thumb_prev", function(e){    
    if(img_arr_pos>0) 
    {
      img_arr_pos--; 
      
      $("#extracted_thumb").html('<img src="'+extracted_images[img_arr_pos]+'">');

      $("#url_image").attr('value', extracted_images[img_arr_pos]);
      
      $("#total_imgs").html((img_arr_pos) +' of '+ total_images);
    }
  });
  
  $("body").on("click","#thumb_next", function(e){    
    if(img_arr_pos<total_images)
    {
      img_arr_pos++;
      
      $("#extracted_thumb").html('<img src="'+extracted_images[img_arr_pos]+'">');

      $("#url_image").attr('value', extracted_images[img_arr_pos]);
      
      $("#total_imgs").html((img_arr_pos) +' of '+ total_images);
    }
  });


   $("body").on("click", ".js_publisher_tab", function() {
        var tab = $(this).attr("data-tab");
        $(".js_publisher_plugin_tab").removeClass("active");
        if(tab == "post") {
            if($(this).hasClass("active")) { return; }
            $(".js_publisher_tab").removeClass("active");
            $(this).addClass("active");
			     
            $("#album-form").hide();
            $("#album-form").find("input").val("");
			$(".postText").css('height', '75px');
			$(".publisher-box-footer").slideDown(100);
			
        } else if (tab == "album") {
		    if($(this).hasClass("active")) { return;}
			$(".js_publisher_tab").removeClass("active");
            $(this).addClass("active");

            //$("#album-form").slideToggle("fast");
            //$("#album-form").find("input").focus();
			  $(".postText").css('height', '75px');
			  $(".publisher-box-footer").slideDown(100);
		}
	});	
   
});
function Wo_RemoveFetchedUrl() {
  var content = $('form.publisher-box').find('.extracted_url');
  content.slideUp(function () {
    $(this).remove();
  });
}
function Wo_OpenAlbum() {
  $('#album-form').slideToggle(200);
}
function Wo_ShowFeelings() {
  if ($('.feelings-type-to').is(':empty')) {
    $('.feeling-types').slideToggle(200);
  }
  
}
var pac_input2 = document.getElementById('feelings-text');
function Wo_ShowFeelingType(type, text, placeholder, icon) {
  $('.feeling-types').slideUp(200, function () {
    $('.feelings-type-to').html('<i class="fa fa-' + icon + '"></i> ' + text + '');
    $('#feelings-text').attr('placeholder', placeholder).focus();
    $('#feeling-type').val(type);
    if (type != 'feelings') {
      $('#feelings-text').attr('readonly', false);
    }
    if (type == 'traveling') {
      var autocomplete = new google.maps.places.Autocomplete(pac_input2);
    } else {
      google.maps.event.clearInstanceListeners(pac_input2);
    }
    $('.' + type).slideToggle(200);
  });
}
function Wo_RestFeelings() {
  $('.feelings-type-to, .feelings-value').empty();
  $('#feelings-text').val('');
  $('#feelings-text').attr('readonly', true);
  $('#feelings-text').attr('placeholder', "<?php echo $wo["lang"]["feel_d"]?>");
  $('.feeling-type, .feelings-type').slideUp(200);
  google.maps.event.clearInstanceListeners(pac_input2);
  Wo_ShowFeelings();
}
function Wo_AddFeeling(type, text, icon) {
  $('#feelings-text').val(type);
  $('.feelings-value').html('<span><i class="twa-lg twa twa-' + icon + '"></i> ' + text + '</span>')
  Wo_ShowFeelingType('feelings', 'Feeling', 'What are you feeling ?', 'smile-o');
}
function smokeTheAt(str) {
  var n = str.search("@");
  if(n != "-1"){
    alert('sd');
  }
}

function Wo_AddAnswer() {
  answer_id = 0;
  $('.answers').find('input').each(function (index_id) {
     answer_id = Number(index_id) + 1;
  });
  var last_answer_id = (Number(answer_id) + 1);
  if (last_answer_id < 9) {
     $('.answers').append('<input name="answer[]" type="text" class="form-control" placeholder="<?php echo $wo['lang']['answer'] ?> ' + last_answer_id + '">');
     if (last_answer_id == 8) {
      $('#add_answer').hide();
     }
     $('.answers').find('input:last').focus();
  } else {
     $('#add_answer').hide();
  }
  
}

function Wo_ShowPosInfo() {
  $(".postText").css('height', '75px');
  $(".publisher-box-footer").slideDown(100);
}
 function Wo_ResetAnswers() {
    $('.answers').find('input').each(function (index_id) {
       $(this).val('');
    });
    $('#poll-form').slideUp(200);
  }
</script>
<style>.pac-item > span:last-child {
    display: none;
}</style>