<?php
                global $sqlConnect;
				$item_id = ( isset($_POST['item_id']) ? $_POST['item_id'] : ( isset($_GET['item_id']) ? $_GET['item_id'] : '0' ) );
		  
        if($wo['system']['setting_userpoints_enable_offers'] == 1){               
			   
			   if($item_id == 0){
			   
			   $p = ( isset($_POST['p']) ? $_POST['p'] : ( isset($_GET['p']) ? $_GET['p'] : 1 ) );
			   $search = ( isset($_POST['search']) ? $_POST['search'] : ( isset($_GET['search']) ? $_GET['search'] : '' ) );
			   $tag = ( isset($_POST['tag']) ? $_POST['tag'] : ( isset($_GET['tag']) ? $_GET['tag'] : '' ) );
			   
			   $items_per_page = 10;

			   $filters = array();
			   $search != ""    ? $filters[] = "title LIKE '%$search%'" :0;
			   $tag != ""   ? $filters[] = "tags LIKE '%$tag%'" :0;

			   !empty($filters)  ? $sql_body .= " WHERE " . implode( " AND ", $filters):0;

			   
			   $sql = "SELECT * FROM userpointearner WHERE enabled != 0 AND cant != 0 AND type >= 100 ";

			   if($search){ $sql .= " AND title LIKE '%$search%'"; }			    
			   else if($tag){ $sql .= " AND tags LIKE '%$tag%'"; } 			   
               $resource = $sqlConnect->query($sql);
			   
			   /* COUNT QUERY */
			   $total_items = $resource->num_rows;	   

			   $sql .= " LIMIT $items_per_page";
			   
			   $upearner = new upearner(0);
			   $upearner->upearner_exists = 1;
			   $items = array();
			   $resource = $sqlConnect->query( $sql );
			   
			   //echo json_encode($resource->num_rows);
			   while($row = $resource->fetch_assoc()) {
			         $upearner->upearner_info['id'] = $row['id'];
  			         $upearner->upearner_info['photo'] = $row['photo'];
					 $upearner->upearner_info['ext'] = $row['ext'];
				     $row['photo'] = $upearner->public_photo( '../assets/plugins/img/no_photo.jpg');
  			         // decode html
    			     $row['body'] = html_entity_decode( str_replace("\r\n", "", $row['body']) , ENT_QUOTES, 'UTF-8' );
 			         $items[] = $row;
			   }

			   $tags = soft::db_query_count("SELECT GROUP_CONCAT(tags) FROM userpointearner WHERE enabled = 1");
			   $tagcloud = new tagcloud($tags);

			   /* assign variables */
			   $tagcloud = $tagcloud->to_html('./user_points_offers');
			   
			   } else { // item_id != 0
			   
			   $upearner = new upearner( $item_id );
			   $upearner->upearner_info['photo'] = $upearner->public_photo( '../assets/plugins/img/no_photo.jpg');

			   if($upearner->upearner_exists == 0) {  header("Location: user_points_offers"); exit(); }
			  
			   // UPDATE ENTRY VIEWS
			   $sqlConnect->query( "UPDATE userpointearner SET views = views + 1 WHERE id = ".$item_id);
			   }			   
        }
?>
  <div class="panel panel-default points_content">      
		<?php if($item_id == 0){ ?>            
					<div class="panel-heading light clearfix mt5">
                        <div class="col-sm-7">
                            <strong><?php echo $wo['lang']['plugin_point_offers']; ?></strong>
						</div>	                     
                    </div>
					<div class="panel-body alert alert-info tac"><?php echo $wo['lang']['plugin_point_offers_u_desc']; ?>.</div>
                <div class="panel-body">	
						
				<div class="row">			
                   <?php if($total_items == 0){ ?> <div class="tac"><?php echo $wo['lang']['plugin_point_no_available_offers']; ?>.</div>
			       <?php } else { ?>
				        <ul> 
						<?php foreach($items as $item){ ?>							 			 						 							 					 
  		                   <div class="panel clearfix body_offert">
	 		                    <a href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=user_points_offers&item_id=<?php echo $item['id']; ?>" target="_blank">
			                   	  <div class="col-sm-4">
      		                         <img src="<?php echo $wo['config']['site_url'].'/upload/'.$item['photo']; ?>" alt="<?php echo $item['title']; ?>">   
			        	          </div>
     		                      <div class="col-sm-8">
			        	      	     <div><strong><?php echo $item['title']; ?></strong></div>
			        	      	     <div><?php echo $item['body']; //|regex_replace:"/&#039;/":"'"|truncate:200:"..":true ?></div>
							      	 <div><i class="fa fa-star fa-fw pr10"></i> <?php echo $wo['lang']['plugin_point_click_and_get']; ?> <?php echo $item['cost']; ?> <?php echo $wo['lang']['plugin_point_points_free']; ?></div>
						      		 <div><?php echo $wo['lang']['plugin_point_views']; ?>:<?php echo $item['views']; ?>,  <?php echo $wo['lang']['plugin_point_available']; ?>:<?php echo $item['cant']; ?></div>
    		                       </div>
		        	             </a>	
 		                   </div>		        		 					 
						<?php } ?>
						</ul>
		        	<?php } ?>
		        </div>
						
         </div>
		 <?php } else { ?>
		            <div class="panel-body clearfix body_offerts">
						 <form class="js_ajax_forms form-horizontal" data-url="?f=points&s=offers" action="<?php echo $wo['config']['site_url']; ?>/plugin_requests.php?f=points&s=offers" method="post">  			            
						 	<div>
      		                   <img src="<?php echo $wo['config']['site_url'].'/upload/'.$upearner->upearner_info['photo']; ?>" alt="<?php echo $upearner->upearner_info['title']; ?>">   
			        	     </div>
     		                <div>
			        		     <div><strong><?php echo $upearner->upearner_info['title']; ?></strong></div>
			        		     <div><?php echo $upearner->upearner_info['body']; ?></div>
								 <div class="mt20"><i class="fa fa-star fa-fw pr10"></i> <?php echo $wo['lang']['plugin_point_win']; ?> <?php echo $upearner->upearner_info['cost']; ?> <?php echo $wo['lang']['plugin_point_points_free']; ?></div>
								 
								 <?php if($upearner->upearner_info['cost'] > 0){ ?>
								 	<?php if($upearner->upearner_info['cant'] > 0){ ?>
									 <div class="pull-right flip">
									 <button class="btn btn-success no_radius" type="submit"><?php echo $wo['lang']['plugin_point_participate']; ?></button>
									 <input type="hidden" name="item_id" value="<?php echo $upearner->upearner_info['id']; ?>">
									 <input type="hidden" name="task" value="dobuy">									 
									 </div>
  								    <?php } ?>
								 <?php } ?>
								 <div><?php echo $wo['lang']['plugin_point_available']; ?>: <?php echo $upearner->upearner_info['cant']; ?></div>
								 <div><?php echo $wo['lang']['plugin_point_views']; ?>:<?php echo $upearner->upearner_info['views']; ?></div>
    		               </div>
			<div class="col-xs-12">			   
			<?php /* success */ ?>
            <div class="alert alert-success mb0 mt10 x-hidden" role="alert"></div>
            <?php /* success */ ?>
            <?php /* error */ ?>
            <div class="alert alert-danger mb0 mt10 x-hidden" role="alert"></div>
            <?php /* error */ ?>
			</div>
 		                </form>
				  </div>
		 <?php } ?>
   </div>