<style>
 .mdbtn {position: relative;overflow: hidden;box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26);-webkit-transition: all 0.3s cubic-bezier(0.55, 0, 0.55, 0.2);transition: all 0.3s cubic-bezier(0.55, 0, 0.55, 0.2);text-transform: uppercase;cursor: pointer;min-height: 36px;min-width: 88px;text-align: center;border-radius: 3px !important;box-sizing: border-box;-webkit-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;border: 0;padding: 0px 20px;margin: 6px 0px;line-height: 36px;white-space: nowrap;font-weight: 500;font-size: 14px;font-style: inherit;font-variant: inherit;font-family: inherit;letter-spacing: 0.010em;}
         .navbar-default {
            background: #fff; border: none;height:50px;box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
         }
 .result-bar{
            background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
         }
         .avtive {border-color: <?php echo $wo['config']['btn_background_color'];?> !important;}
         #bar_loading {
            background-color: #2196F3 !important;
         }
 .left-sidebar ul li a i {color: <?php echo $wo['config']['btn_background_color'];?> !important;}
 .cs-loader-inner,  .main  {
  color: <?php echo $wo['config']['btn_background_color'];?>;
 }
  .login input:focus {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
  }
  .login:not(.loading) button:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?>;
  }
  .login button {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?> !important;
  }
 .mejs-controls .mejs-time-rail .mejs-time-current, 
 .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current,
 .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    background-image: <?php echo $wo['config']['btn_background_color'];?> !important;
 }
 .navbar-default .navbar-nav>.open>a,
         .navbar-default .navbar-nav>.open>a:focus,
         .navbar-default .navbar-nav>.open>a:hover {
            color: #000 !important;
            background-color: #d2d2d2 !important;
         }
 .navbar-default .navbar-nav>.active>a,
 .navbar-default .navbar-nav>.active>a:focus,
 .navbar-default .navbar-nav>.active>a:hover,
 .nav-names li:hover {
   color: <?php echo $wo['config']['header_color'];?> !important;
   background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
 }
 body {
   background-color: #e9eaed;
 }
 .navbar-default .navbar-nav>li>a {
            color: #888;
            font-size: 13px;
         }
         a.unread-update {
            color: #3a3a3a  !important;
         }
 .btn-main {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .admin-panel .col-md-9 .list-group-item:first-child, 
         .setting-panel .col-md-8 .list-group-item:first-child, 
         .profile-lists .list-group-item:first-child, 
         .col-sm-4 .list-group-item:first-child,
         .red-list .list-group-item:first-child,
         .active.list-group-item:first-child {
             color: #444;
             background-color: #fcfcfc;
             border-bottom: 1px solid #f1f1f1;
             padding: 18px;
         }
         .admin-panel .col-md-9 .list-group-item:first-child a, 
         .setting-panel .col-md-8 .list-group-item:first-child a, 
         .profile-lists .list-group-item:first-child a, 
         .col-md-8 .list-group-item:first-child a,
         .col-md-7 .list-group-item:first-child a,
         .active.list-group-item:first-child a {
            color: #444 !important;
         }
 .list-group-item.black-list.active-list, .red-list.active-list {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .list-group-item.black-list {
     background: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .profile-top-line {
     background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 #bar {
     background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .list-group-item.black-list a{
     color: <?php echo $wo['config']['btn_color'];?>;
 }
 .list-group-item.black-list.active-list a{
     color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .main-color, .small-text a {
     color: <?php echo $wo['config']['btn_background_color'];?> !important;
 }
 .search-advanced-container a:hover {
    text-decoration: none;
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .nav-tabs>li.active>a,
 .nav-tabs>li.active>a:focus,
 .nav-tabs>li.active>a:hover {
    color: <?php echo $wo['config']['btn_color'];?>;
    cursor: default;
    color: <?php echo $wo['config']['btn_background_color'];?>;
    border-bottom: 1px solid <?php echo $wo['config']['btn_background_color'];?>;
    background-color: transparent
 }
 .btn-active {
    color: <?php echo $wo['config']['btn_color'];?>;
    background: <?php echo $wo['config']['btn_background_color'];?>;
    outline: none;
    border: 1px solid <?php echo $wo['config']['btn_background_color'];?>
 }
 .btn-active:hover, .btn-active:focus {
    border: 1px solid <?php echo $wo['config']['btn_hover_background_color'];?>;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .btn-active-color:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .chat-container {
    background: <?php echo $wo['config']['body_background'];?> !important;
 }
 .chat-tab .online-toggle {
    background: #4CAF50;
 }
 .profile-style .user-follow-button button.btn-active,
 .btn-login,
 .btn-register {
    background: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
 }
 .profile-style .user-follow-button button.btn-active:hover,
 .btn-login:hover,
 .btn-login:focus,
 .btn-register:hover,
 .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 button:disabled  {
    background-color: <?php echo $wo['config']['btn_disabled'];?> !important;
 }
 .panel-login>.panel-heading a.active {
    color: <?php echo $wo['config']['btn_background_color'];?>;
    font-size: 18px;
 }
 .hash {
    color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .sixteen-font-size {
    color: #888 !important;
 }
 /*.search-container .search-input {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background: <?php echo $wo['config']['header_search_color'];?> !important;
 }*/
 .chat-messages-wrapper .outgoing {
     background: <?php echo $wo['config']['chat_outgoing_background'];?>;
 }
 .normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
/*.post-privacy-menu li a:hover, .post-privacy-menu li div:hover {
  color: <?php echo $wo['config']['btn_color'];?>;
  background-color: <?php echo $wo['config']['btn_background_color'];?>;
}*/
.active.fa-thumbs-up {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
/*.post-privacy-menu li a:hover, .post-privacy-menu li div:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>; }*/
.api-ex-urls {
    background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>;
}
.user-username {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.upload-image {
    border: 3px dashed <?php echo $wo['config']['btn_background_color'];?>;
}
.events-tab-list li { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.events-tab-list li:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.active-e-tab { background-color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.main { color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.events-list-dropup-menu ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?>; }
.products .product .product-links .more-info, .usr-offline { color: <?php echo $wo['config']['btn_background_color'];?>; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?> !important; }
.blog_publ {background: <?php echo $wo['config']['btn_background_color'];?> ; border: 1px solid <?php echo $wo['config']['btn_background_color'];?> ; }
</style>