<style>
    .cv-log-reg{
        margin-top: 16px;
    }
    .cv-log-reg .a-login{
        color: #17aa9d;
        font-size: 14px;
        margin-right: 15px;
    }
    .cv-log-reg .a-reg{
        color: #17aa9d;
        font-size: 14px;
    }
    .cv-log-reg img{
        width: 15px;
    }
</style>
<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?>">
   <!--<li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <i class="fa fa-user"></i> <?php /*echo $wo['lang']['guest']; */?>
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
         <li>
            <a href="<?php /*echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);*/?>">
            <?php /*echo $wo['lang']['login']; */?>
            </a>
         </li>
         <li>
            <a href="<?php /*echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);*/?>">
            <?php /*echo $wo['lang']['register']; */?>
            </a>
         </li>
      </ul>
   </li>-->
    <div class="cv-log-reg">
        <a class="a-login" href="<?php echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);?>"><img src="<?php echo $wo['config']['theme_url'];?>/img/icon-login.png"/> Login</a>
        <a class="a-reg" href="/register"><img src="<?php echo $wo['config']['theme_url'];?>/img/icon-reg.png"/> Register</a>
    </div>
</ul>