<tr class="setting-userlist" id="UserID_<?php echo $wo['userlist']['user_id']?>" data-user-id="<?php echo $wo['userlist']['user_id']?>">
   <td><?php echo $wo['userlist']['user_id']?></td>
   <td>
      <a href="<?php echo $wo['userlist']['url']; ?>">
      <img src="<?php echo $wo['userlist']['avatar']; ?>" class="setting-avatar" alt="<?php echo $wo['userlist']['avatar']?> Profile Picture">
      <?php echo $wo['userlist']['name']; ?>
      </a>
   </td>
   <td><?php echo $wo['userlist']['src']?></td>
   <td><?php echo $wo['userlist']['email']?></td>
   <td><?php echo $wo['userlist']['ip_address']?></td>
   <td><?php echo (Wo_UserActive($wo['userlist']['username']) === true) ? '<span class="label label-success">' . $wo['lang']['active'] . '</span>': '<span class="label label-danger">' . $wo['lang']['pending'] . '</span>';?></td>
   <td>
      <span class="pointer">
      <a target="_blank" href="<?php echo Wo_SeoLink('index.php?link1=setting&user=' . $wo['userlist']['username'] . '&page=general-setting') ?>">
      <i class="fa fa-pencil-square"></i>
      </a>
      </span> |
      <span class="pointer" onclick="Wo_DeleteUser(<?php echo $wo['userlist']['user_id']?>);">
      <i class="fa fa-trash-o"></i>
      </span>
   </td>
</tr>