<div class="sidebar-conatnier">
   <div class="home profile-style sidebar-profile-style main">
      <div class="card hovercard">
         <div class="cardheader">
            <img src="<?php echo $wo['setting']['cover']?>" id="cover-image" alt="<?php echo $wo['setting']['name']?> Cover Image">
         </div>
         <div class="avatar ">
            <img id="updateImage-<?php echo $wo['setting']['user_id']?>" alt="<?php echo $wo['setting']['name']?> Profile Picture" src="<?php echo $wo['setting']['avatar']?>">
         </div>
         <div class="info">
            <div class="title">
               <a id="user-full-name" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['setting']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>"><?php echo $wo['setting']['name']?></a>
               <?php if($wo['setting']['verified'] == 1):?>
               <i class="fa fa-check-circle verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
               <?php endif;?>
            </div>
         </div>
      </div>
   </div>
   <ul class="list-group filterby settings-by">
            <li class="list-group-item hidden" contenteditable="false">Settings</li>
            <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'general-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=general-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=general-setting"><?php echo $wo['lang']['general'];?></a></li>
            <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'profile-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=profile-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=profile-setting"><?php echo $wo['lang']['profile'];?></a></li>
           
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'privacy-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=privacy-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=privacy-setting"><?php echo $wo['lang']['privacy'];?></a></li>
           
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'change-password-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=change-password-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=change-password-setting"><?php echo $wo['lang']['password'];?></a></li>

           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'social-links') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=social-links');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=social-links"><?php echo $wo['lang']['social_links'];?></a></li>
           
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'avatar-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=avatar-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=avatar-setting"><?php echo $wo['lang']['avatar_and_cover'];?></a></li>

           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'design-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=design-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=design-setting"><?php echo $wo['lang']['design'];?></a></li>

           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'blocked-users') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=blocked-users');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=blocked-users"><?php echo $wo['lang']['blocked_users'];?></a></li>
           
           <?php if ($wo['config']['emailNotification'] == 1) {?>
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'email-setting') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=email-setting');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=email-setting"><?php echo $wo['lang']['email_notification'];?></a></li>
           <?php } ?>
            
           <?php if ($wo['config']['affiliate_system'] == 1) {?>
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'affiliates') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=affiliates');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=affiliates"><?php echo $wo['lang']['my_affiliates'];?></a></li>
           <?php } ?>
           <?php if ($wo['config']['deleteAccount'] == 1) {?>
           <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'delete-account') ? 'avtive': '';?>" dir="auto"><a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=delete-account');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=delete-account"><?php echo $wo['lang']['delete_account'];?></a></li>
           <?php } ?>

        </ul>
   <?php echo Wo_LoadPage('footer/sidebar-footer')?>
</div>