<div class="page-margin">
   <div class="row">
      <div class="col-md-8">
         <div class="list-group red-list">
            <div class="list-group-item"> </div>
            <div class="setting-well">
               <form class="contact-us-form form-horizontal" method="post">
			   
			   <div style="text-align:center">
			   <svg version="1.1" width="60" height="60" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<rect x="154.748" y="133.35" style="fill:#FF8564;" width="349.684" height="245.301"/>
<polyline style="fill:#FFFFFF;" points="504.432,133.35 329.59,254.434 154.748,133.35 "/>
<path d="M146.659,125.521v33.925H0v15.658h146.659v73.068H25.052v15.657h121.607v28.705H48.016v15.657h98.642v78.287H512V125.521
	H146.659z M496.342,370.822H162.316V148.295l167.01,115.661l123.14-85.169l-8.907-12.878l-114.227,79.006L179.543,141.178h316.799
	V370.822z"/>
<rect x="461.617" y="149.621" transform="matrix(-0.5703 -0.8214 0.8214 -0.5703 607.8459 632.8602)" width="15.657" height="15.657"/>
<rect y="336.897" width="15.657" height="15.657"/>
<rect x="33.925" y="336.897" width="97.598" height="15.657"/>
<rect y="203.808" width="15.657" height="15.657"/>
<rect x="33.925" y="203.808" width="97.598" height="15.657"/>
</svg>
<br><?php echo $wo['lang']['contact_us']; ?>
			   </div>
			   
                  <fieldset>
                     <div class="contact-us-alert setting-update-alert"></div>
                     <!-- Text input-->
                     <div class="form-group">
                        <label class="col-md-3" for="first_name"><?php echo $wo['lang']['first_name'];?> *</label>  
                        <div class="col-md-6">
                           <input id="first_name" name="first_name" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <!-- Text input-->
                     <div class="form-group">
                        <label class="col-md-3" for="last_name"><?php echo $wo['lang']['last_name'];?> *</label>  
                        <div class="col-md-6">
                           <input id="last_name" name="last_name" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <div class="form-group">
                        <label class="col-md-3" for="email"><?php echo $wo['lang']['email'];?> *</label>  
                        <div class="col-md-6">
                           <input name="email" id="email" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <div class="form-group">
                        <label class="col-md-3" for="message"><?php echo $wo['lang']['message'];?> *</label>  
                        <div class="col-md-6">
                           <textarea name="message" id="message" rows="5" class="form-control input-md"></textarea>
                        </div>
                     </div>
                     <hr>
                     <div class="form-group last-btn">
                        <label class="col-md-3"></label>
                        <div class="col-sm-3 text-left">
                           <button type="submit" name="send" id="send" tabindex="4" class="mdbtn form-control btn btn-main">
                           <i class="fa fa-paper-plane-o progress-icon" data-icon="paper-plane-o"></i> <?php echo $wo['lang']['send'];?>
                           </button>
                        </div>
                     </div>
                  </fieldset>
               </form>
            </div>
         </div>
      </div>
      <!-- .col-md-8 -->
      <?php
         if ($wo['loggedin'] == true) {
          echo Wo_LoadPage('sidebar/content');
         } else {
          echo Wo_LoadPage('sidebar/guest');
         }
         ?>
   </div>
   <!-- .row -->
</div>
<!-- .page-margin -->
<script>
   $(function() {
     $('form.contact-us-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=contact_us',
       beforeSend: function() {
         Wo_progressIconLoader($('form.contact-us-form').find('button'));
       },
       success: function(data) {
         if (data.status == 200) {
            $('.contact-us-alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('.alert-success').fadeIn(300);
         } else {
             var errors = data.errors.join("<br>");
             $('.contact-us-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         Wo_progressIconLoader($('form.contact-us-form').find('button'));
       }
     });
   });
</script>