<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-plus"></i>Add new language</div>
   <div class="setting-well page-margin">
      <form action="" method="post" class="admin-site-setting form-horizontal">
         <div class="form-group">
            <label class="col-md-3" for="lang">Language name:</label>  
            <div class="col-md-6">
               <input type="text" class="form-control" name="lang"> 
               <span class="help-block">Use only english letters, example: russian</span>
            </div>
         </div>
         <hr>
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
         <div class="form-group">
            <label class="col-md-3"></label>  
            <div class="col-md-6">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-plus progress-icon" data-icon="plus"></i>  <?php echo $wo['lang']['add']?>
               </button> 
               <span class="help-block">Note: This may take up to 5 minutes.</span>
            </div>
         </div>
      </form>
   </div>
</div>
<script type="text/javascript">
$(function() {
    $('form.admin-site-setting').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_lang',
      beforeSend: function() {
        Wo_progressIconLoader($('form.admin-site-setting').find('button'));
      },
      success: function(data) {
        if (data.status == 200) {
          $('form.admin-site-setting button').html('<i class="fa fa-check"></i> Added');
          setTimeout(function () {
            window.location.href = '<?php echo Wo_SeoLink("index.php?link1=admincp&page=languages");?>';
          }, 1000);
        } else if (data.status == 400) {
          alert(data.message);
        }
        Wo_progressIconLoader($('form.admin-site-setting').find('button'));
      }
    });
});

</script>