<div class="chat-wrapper chat_<?php echo $wo['chat']['recipient']['user_id'];?>" id="chat_<?php echo $wo['chat']['recipient']['user_id'];?>">
   <div style="background:<?php echo $wo['chat']['color']; ?>" class="online-toggle pointer" onclick="javascript:$('.chat-tab-container-<?php echo $wo['chat']['recipient']['user_id'];?>').slideToggle(100);">
      <a style="color:#fff;" href="<?php echo $wo['chat']['recipient']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['chat']['recipient']['username'];?>"> 
      <span class="chat-tab-status <?php echo (Wo_IsOnline($wo['chat']['recipient']['user_id']) === true) ? 'active' : ''; ?>"><i class="fa fa-circle fa-fw"></i></span><?php echo mb_substr($wo['chat']['recipient']['name'], 0, 20, "UTF-8");?>
      </a>
      <span class="<?php echo Wo_RightToLeft('pull-right');?> close-chat">
      <?php if ($wo['config']['audio_chat'] == 1) { ?>
      <?php if ($wo['chat']['recipient']['lastseen'] > (time() - 60)) { ?>
      <i class="fa fa-phone" onclick="Wo_GenerateVoiceCall(<?php echo $wo['user']['user_id'];?>, <?php echo $wo['chat']['recipient']['user_id'];?>)"></i>&nbsp;
      <?php } else { ?>
      <i class="fa fa-phone" style="color:#999;" title="Not availabe"></i>&nbsp;
      <?php } } ?>
      <?php if ($wo['config']['video_chat'] == 1) { ?>
      <?php if ($wo['chat']['recipient']['lastseen'] > (time() - 60)) { ?>
      <i class="fa fa-video-camera" onclick="Wo_GenerateVideoCall(<?php echo $wo['user']['user_id'];?>, <?php echo $wo['chat']['recipient']['user_id'];?>)"></i>&nbsp;
      <?php } else { ?>
      <i class="fa fa-video-camera" style="color:#999;" title="Not availabe"></i>&nbsp;
      <?php } } ?>
      <a class="white" data-ajax="?link1=messages&user=<?php echo $wo['chat']['recipient']['user_id'];?>" href="<?php echo Wo_SeoLink("index.php?link1=messages&user=" . $wo['chat']['recipient']['user_id']);?>">
      <i class="fa fa-external-link-square"></i>&nbsp;
      </a>
      <i class="fa fa-times-circle" onclick="Wo_CloseChat(<?php echo $wo['chat']['recipient']['user_id'];?>);"></i>
      </span>
   </div>

   <div class="chat-tab-container chat-tab-container-<?php echo $wo['chat']['recipient']['user_id'];?> chat-tab-box-<?php echo $wo['chat']['recipient']['user_id'];?>">
      <div class="chat-messages-wrapper chat-messages-wrapper-<?php echo $wo['chat']['recipient']['user_id'];?>">
         <div class="chat-messages">
           <div class="chat-user-desc">
             <div class="row">
                <div class="col-sm-4">
                  <img src="<?php echo $wo['chat']['recipient']['avatar'];?>" alt="User avatar">
                </div>
                <div class="col-sm-8">
                  <div class="text">
                    <span class="head-text">
                    <?php $is_following = Wo_IsFollowing($wo['chat']['recipient']['user_id'], $wo['user']['user_id']);?>
                    <?php if ($wo['config']['connectivitySystem'] == 0) { ?>
                      <?php if ($is_following) { ?>
                         <?php echo $wo['lang']['your_following'];?> <?php echo $wo['chat']['recipient']['name'];?>
                      <?php } ?>
                    <?php } else { ?>
                      <?php 
                      if ($is_following) { 
                        echo $your_friends = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['your_friends_chat']);
                      } 
                      ?>
                    <?php } ?>
                    </span>
                    <?php 
                    $country = $wo['chat']['recipient']['country_id'];
                    if ($country > 0) {
                    ?>
                    <div class="desc-text"><i class="fa fa-home fa-fw"></i> <?php echo $wo['lang']['living_in'];?> <?php echo $wo['countries_name'][$country];?></div>
                    <?php } ?>
                    <?php 
                    $working = $wo['chat']['recipient']['working'];
                    if (!empty($working)) {
                    ?>
                    <div class="desc-text"><i class="fa fa-fa fa-briefcase fa-fw"></i> <?php echo $wo['lang']['working_at'];?> <?php echo $working;?></div>
                    <?php } ?>
                  </div>
                </div>  
             </div>
           </div>
         </div>

         <div class="clear"></div>
      </div>
      <div class="chat-textarea btn-group">
         <div class="emo-container emo-container-<?php echo $wo['chat']['recipient']['user_id'];?>">
            <?php  
            foreach ($wo['emo'] as $code => $name) {
              $code   = $code;
              echo  '<span onclick="Wo_AddEmoToChat(\'' . $code . '\', ' . $wo['chat']['recipient']['user_id'] . ');"><i class="pointer twa-lg twa twa-' . $name . '"></i></span>'; 
            } 
            ?>
         </div>


         <form action="#" method="post" class="chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>">
            <textarea name="textSendMessage" id="sendMessage" class="form-control" cols="10" rows="5" placeholder="<?php echo $wo['lang']['write_something'];?>"  onkeydown="Wo_SubmitChatForm(event, <?php echo $wo['chat']['recipient']['user_id'];?>);" onfocus="Wo_SubmitChatForm(event, <?php echo $wo['chat']['recipient']['user_id'];?>);" dir="auto" ></textarea>

            <div class="w-10 chat-btns-w" style="padding: 0 10px;">
            <span>
              <span class="btn btn-file" id="progressIcon" style="padding: 3px;">
              <?php if($wo['config']['fileSharing'] == 1) { ?>
              <i class="fa fa-file-text-o progress-icon" data-icon="file-text-o"></i>
              <input type="file" id="sendMessasgeFile" name="sendMessageFile" class="pointer" onchange="Wo_ShareChatFile(<?php echo $wo['chat']['recipient']['user_id'];?>);" />
              <?php } else { ?>
              <i class="fa fa-picture-o  progress-icon" data-icon="picture-o"></i>
              <input type="file" id="sendMessasgeFile" name="sendMessageFile" onchange="Wo_ShareChatFile(<?php echo $wo['chat']['recipient']['user_id'];?>);" accept="image/x-png, image/gif, image/jpeg"  />
              <?php } ?>
              </span>
            </span>

            <span class="emo-btn-<?php echo $wo['chat']['recipient']['user_id'];?>" style="<?php echo Wo_RightToLeft('right');?>:60px;">
              <span class="btn btn-file" style="padding: 3px;">
                 <i class="fa fa-smile-o progress-icon" data-icon="file-smile-o"></i>
              </span>
            </span>
            <span class="dropup dropdown">
              <span class="btn btn-file dropdown-toggle" style="padding: 3px; "  data-toggle="dropdown" aria-expanded="true" role="button">
                 <i class="fa fa-circle select-color" aria-hidden="true" style="color: <?php echo $wo['chat']['color']; ?>"></i>
              </span>
              <ul class="dropdown-menu drop-up" role="menu">
                <li>
                  <div class="chat-colors-cont text-center">
                    <?php foreach ($wo['colors'] as $key => $color) {?>
                    <a class="chat-color" data-chat-color="<?php echo $color; ?>"  data-recipient-u-id="<?php echo $wo['chat']['recipient']['user_id'];?>" style="color: <?php echo $color; ?>;">
                      <i class="fa fa-circle" aria-hidden="true"></i>
                    </a>
                    <?php } ?>
                  </div>
                </li>
              </ul>
            </span>
            </div>
            <input type="hidden" id="user-id" class="chat-user-id" name="user_id" value="<?php echo $wo['chat']['recipient']['user_id'];?>" />
            <input type="hidden" id="color" value="<?php echo $wo['chat']['color'];?>" />
         </form>
      </div>
   </div>
</div>

<script type="text/javascript">
jQuery(document).ready(function($) {
    $(".chat-colors-cont a").click(function(event) {
      var recipient_id = $(this).attr('data-recipient-u-id');
      $.ajax({
        url:  Wo_Ajax_Requests_File(),
        type: 'get',
        data:{f:'chat',s:'set-chat-color',color:$(this).attr('data-chat-color'),recipient_user:$(this).attr('data-recipient-u-id')},
        dataType: 'json',
        success: function(data){
          if (data['status'] == 200) {
             $(".chat_" + recipient_id).find('.online-toggle, .outgoing').css('background', data['color']);
             $(".chat_" + recipient_id).find('.online-toggle, .outgoing').css('color', '#fff');
             $(".chat_" + recipient_id).find('.select-color').css('color', data['color']);
             $(".chat_" + recipient_id).find('#color').val(data['color']);
          }
        }
      });
    });
});

$(function() {



    var main_hash_id = $('.main_session').val();
    $('.emo-btn-<?php echo $wo['chat']['recipient']['user_id'];?>').click(function () {
        $('.emo-container-<?php echo $wo['chat']['recipient']['user_id'];?>').toggle();
    });
    var chat_messages_wrapper = $('.chat-messages-wrapper-<?php echo $wo['chat']['recipient']['user_id'];?>');
    $('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=chat&s=send_message&hash=' + main_hash_id,
        beforeSend: function() {
            if (chat_messages_wrapper.find('.chat-user-desc').length == 1) {
                chat_messages_wrapper.find('.chat-user-desc').empty();
            }
            var text_message = escapeHTML($('.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?> #sendMessage').val());
            $('.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').attr('disabled', true);
            var color = $('.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?> #color').val();
            <?php  if (!empty($wo['chat']['color'])) { ?>
             var html_message = '<div class="sended_message"><div class="messages-wrapper pull-right messages-text" id="messageId_" data-message-id=""><div class="message outgoing pull-right" style="background: ' + color + ';"><p class="message-text" style="color: #fff" dir="auto">' + text_message + '</p><div class="clear"></div><div class="message-media"></div></div><div class="clear"></div><div class="message-seen text-right message-details"></div><div class="clear"></div><div class="message-typing message-details"></div></div><div class="clear"></div></div>';
            <?php } else { ?>
              var html_message = '<div class="sended_message"><div class="messages-wrapper pull-right messages-text" id="messageId_" data-message-id=""><div class="message outgoing pull-right"><p class="message-text" dir="auto">' + text_message + '</p><div class="clear"></div><div class="message-media"></div></div><div class="clear"></div><div class="message-seen text-right message-details"></div><div class="clear"></div><div class="message-typing message-details"></div></div><div class="clear"></div></div>';
            <?php } ?>
            if (!text_message) {
              $('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').find('#sendMessasgeFile').val('');
              return false;
            }
            $('body').attr('sending-<?php echo $wo['chat']['recipient']['user_id'];?>', true);
            if (text_message && $('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?> #sendMessasgeFile').val() == '') {
              if (chat_messages_wrapper.length == 0) {
                chat_messages_wrapper.html(html_message);
              } else {
                chat_messages_wrapper.append(html_message);
              }
            }
            setTimeout(function() {
                  chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
            }, 100);
            $('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').clearForm();
        },
        uploadProgress: function () {
          Wo_progressIconLoader($('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').find('#progressIcon'));
        },
        success: function(data) {
            if (data.status == 200) {
                chat_messages_wrapper.find("div[class*='message-seen']").empty();
                chat_messages_wrapper.find("div[class*='message-typing']").empty();
                chat_messages_wrapper.find(".sended_message:last").html(data.html);    
            }
            $('body').attr('sending-<?php echo $wo['chat']['recipient']['user_id'];?>', false);
            setTimeout(function() {
              chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
            }, 700);
            if (data.file == true) {
              Wo_progressIconLoader($('form.chat-sending-form-<?php echo $wo['chat']['recipient']['user_id'];?>').find('#progressIcon'));
            }
        }
    });
}); 
function escapeHTML(string) {
    var pre = document.createElement('pre');
    var text = document.createTextNode( string );
    pre.appendChild(text);
    return pre.innerHTML;
}


</script>