<tr class="setting-banlist" id="IPID_<?php echo $wo['ip']['id']?>" >
   <td><?php echo $wo['ip']['id']?></td>
   <td>
      <div class="ajax-time" title="<?php echo date('c',$wo['ip']['time']); ?>">
         <?php echo Wo_Time_Elapsed_String($wo['ip']['time']);?>
      </div>
   </td>
   <td>
     <?php echo $wo['ip']['ip_address']?>
   </td>
   <td>
      <a href='<?php echo Wo_SeoLink("index.php?link1=admincp&page=banned_ip&delete_ip=" . $wo['ip']['id']);?>'>
      <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> <?php echo $wo['lang']['delete']; ?>
      </a>
   </td>
</tr>