<div class="list-group">
   <div class="list-group-item"><i class="fa fa-fw fa-trash"></i><?php echo $wo['lang']['delete_group'];?> <a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['group_name'];?>">(<?php echo $wo['setting']['name'];?>)</a></div>
   <div class="setting-well">
   <form action="#" method="post" class="form-horizontal setting-delete-page-form">
      <fieldset>
         <div class="setting-delete-page-alert setting-update-alert"></div>
         <div class="form-group">
            <label class="col-md-3" for="password"><?php echo $wo['lang']['password']; ?></label>
            <div class="col-md-6">
               <input id="password" name="password" type="password" class="form-control input-md">
            </div>
         </div>
         <input type="hidden" name="group_id" value="<?php echo $wo['setting']['id'];?>">
         <div class="form-group last-btn">
            <label class="col-md-3"></label>
            <div class="col-sm-3 text-left">
               <button type="submit" class="form-control btn btn-main">
               <i class="fa fa-remove progress-icon" data-icon="remove"></i> <?php echo $wo['lang']['delete']; ?>
               </button>
            </div>
         </div>
      </fieldset>
      <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
   </form>
</div>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-delete-page-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=groups&s=delete_group',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-delete-page-form').find('button'));
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-delete-page-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          window.setTimeout(function() {
            window.location.href = data.location;
          },2000);
        });
      } else {
        var errors = data.errors.join("<br>");
        $('.setting-delete-page-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      Wo_progressIconLoader($('form.setting-delete-page-form').find('button'));
    }
  });
});
</script>